<ol class="breadcrumb" >
    <li><a href="" >Dashboard</a></li>
</ol>
<div class="container-fluid">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Tủy Chọn</h3>
            <div class="box-tools">

            </div>
        </div>
        <div class="box-body">
            <a href="/backend/qrcode/" class="btn btn-success" >Mã QRCode Cá Nhân</a>
        </div>
    </div>

</div>