<?php 
$id = $this->getParams(0);
?>

<ol class="breadcrumb">
    <li><a href="/backend/"><i class="fa fa-dashboard"></i>&nbsp; Dashboard</a></li>
    <li><a href="/backend/xuatkho/"> Danh sách thuốc xuất kho</a></li>
    <li class="active">Lịch sử nhập kho của thuốc <?php echo \Module\quanlythuoc\Model\SanPham::GetNameById($id);?></li>
</ol>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-success">
                <div class="box-header">
                    <h3 style="text-align: center;">Lịch sử xuất của thuốc <?php echo \Module\quanlythuoc\Model\SanPham::GetNameById($id);?></h3>
                    <div class="box-tools">
                        <a class="btn btn-success" href="/thongke/exportthuocsaphet">
                            <i class="fa fa-filter"></i> Export</a>
                    </div>
                </div>

                <div class="box-body">
                    <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                        <div class="row">
                            <div class="col-sm-6"></div>
                            <div class="col-sm-6"></div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                                    <thead>
                                        <tr role="row">
                                            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending">STT</th>
                                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Ngày nhập</th>
                                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Số lượng</th>
                                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending">Nhà sản xuất</th>
                                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Số lô</th>
                                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Nước sản xuất</th>
                                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Giá nhập</th>
                                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Tổng giá</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php

                                        use Model\Common;
                                        use Model\Notions;
                                        use Model\ThongKe;
                                        use Module\quanlythuoc\Model\SanPham;
                                        $index = 0;
                                        // echo $id;
                                        $thongke = ThongKe::LichSuXuatById($id);
                                        // var_dump($thongke);
                                        // $sp = new SanPham();
                                        foreach ($thongke as $value) {?>
                                        <?php
                                        // $thuoc = $sp->GetById($value["IdThuoc"]);
                                        ?>
                                            <tr role="row" class="even">
                                                <td class="sorting_1 text-center"><?php echo $index + 1 ?></td>
                                                <td><?php echo Common::ForMatDMYHIS($value['NgayNhap']); ?></td>
                                                <td><?php echo $value['SoLuong']; ?></td>
                                                <td><?php echo $value['NhaSanXuat']; ?></td>
                                                <td><?php echo $value['SoLo']; ?></td>
                                                <td><?php echo $value['NuocSanXuat']; ?></td>
                                                <td><?php echo Common::ViewPrice($value['Price']); ?></td>
                                                <td><?php echo Common::ViewPrice($value['Tong']); ?></td>
                                                
                                            </tr>
                                        <?php
                                            $index++;
                                        }
                                        ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>