<ol class="breadcrumb">
    <li><a href="/index.php?controller=backend">Home</a></li>
    <li><a href="index.php?module=quanlythuoc&controller=danhmuc&action=index"> Danh Mục Thuốc</a></li>
    <li> Thêm Danh Mục </li>
</ol>
<?php

use Module\quanlythuoc\Model\DanhMuc;
use Module\quanlythuoc\Model\DanhMuc\FormDanhMuc;


$roleDetail = new Model\Role();
?>
<div class="container-fluid">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Thêm Danh Mục</h3>
            <div class="box-tools">
                <?php
                Module\quanlythuoc\Model\btnHtml::btnViewDanhMuc();
                ?>
                <a class="btn btn-warning" target="_self" data-toggle="modal" href='#modal-id'>
                        <i class="fa fa-info" aria-hidden="true"></i>
                    </a>
                    <div class="modal fade" id="modal-id">
                        <div class="modal-dialog modal-lg">
                            <div class="modal-content">
                                <div class="modal-body">
                                    <?php
                                    if (file_exists("public\huongdan\huongdandanhmuc.html"))
                                        echo file_get_contents("public\huongdan\huongdandanhmuc.html");
                                    ?>
                                </div>
                                <div class="modal-footer">
                                    <a class="btn btn-success" href="/huongdan/huongdandanhmuc/huongdandanhmuc">Sửa hướng dẫn danh mục</a>
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Đóng lại</button>
                                </div>
                            </div>
                        </div>
                    </div>
            </div>
        </div>
        <!-- <div class="box-body"> -->
        <form action="" method="post" enctype="multipart/form-data">
            <div class="box-body">
                <?php
                $dm = new FormDanhMuc();
                ?>
                <div class="">
                    <div class="col-md-6">
                        <?php $dm->Id(DanhMuc::CreatId())->renderHtml(); ?>
                    </div>
                    <div class="col-md-6">
                        <?php $dm->Name()->renderHtml();  ?>
                    </div>
                    <div class="col-md-6">
                        <?php $dm->Link()->renderHtml();  ?>
                    </div>
                    <div class="col-md-6">
                        <?php $dm->GhiChu()->renderHtml();  ?>
                    </div>
                    <div class="col-md-12 ">
                        <button class="btn btn-warning" type="reset">Làm Lại</button>
                        <!-- <button class="btn btn-success">Lưu</button> -->
                        <button class="btn btn-success" name="LuuThoat">Thêm Mới</button>
                    </div>
                </div>
        </form>
    </div>
</div>
</div>