<ol class="breadcrumb">
    <li><a href="/index.php?controller=backend">Home</a></li>
    <li><a href="index.php?module=quanlythuoc&controller=danhmuc&action=index"> Danh Mục Thuốc</a></li>
    <li> Thêm Danh Mục </li>
</ol>
<?php

use Module\quanlythuoc\Model\DanhMuc;
use Module\quanlythuoc\Model\DanhMuc\FormDanhMuc;


$roleDetail = new Model\Role();
?>
<div class="container-fluid">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Thêm Danh Mục</h3>
            <div class="box-tools">
                <!--<a href="#" class="btn btn-success" ><i class="fa fa-plus" ></i></a>-->
            </div>
        </div>
        <!-- <div class="box-body"> -->
        <form action="" method="post" enctype="multipart/form-data">
            <div class="box-body">
                <?php
                $dm = new FormDanhMuc();
                ?>
                <div class="">
                    <div class="col-6">
                        <?php $dm->Id()->render(); ?>
                    </div>
                    <div class="col-md-6">
                        <?php $dm->Code()->renderHtml();  ?>
                    </div>
                    <div class="col-md-6">
                        <?php $dm->Name()->renderHtml();  ?>
                    </div>
                    <div class="col-md-6">
                        <?php $dm->Link()->renderHtml();  ?>
                    </div>
                    <div class="col-md-6">
                        <?php $dm->ThanhPhan()->renderHtml();  ?>
                    </div>
                    <div class="col-md-6">
                        <?php $dm->LuuY()->renderHtml();  ?>
                    </div>
                    <div class="col-md-6">
                        <?php $dm->GhiChu()->renderHtml();  ?>
                    </div>
                    <div class="form-group ">
                        <button class="btn btn-default" type="reset">Làm Lại</button>
                        <!-- <button class="btn btn-success">Lưu</button> -->
                        <button class="btn btn-success" name="LuuThoat">Thêm Mới</button>
                        </div>
                </div>
        </form>
    </div>
</div>
</form>
</div>
</div>
</div>