<ol class="breadcrumb">
    <li><a href="/backend/">Trang chủ</a></li>
    <li> Danh Sách Báo Cáo Thuốc </li>
</ol>

<div class="container-fluid">
    <div class="clearfix">
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title">Báo Cáo Xuất Nhập Thuốc</h3>
            </div>
            <div class="box-body">
                <form method="get" action="/quanlythuoc/baocao/index/">
                    <div class="row">
                        <div class="col-sm-3 form-group">
                            <?php
                            use Model\FormCommon;
                            use Module\quanlythuoc\Model\SanPham;

                            FormCommon::TextBox("Từ Ngày", "FromDate", [
                                "value" => $_GET["FromDate"] ?? "",
                                "type" => "date",
                                "class" => "form-control"
                            ])->renderHTML();
                            ?>
                        </div>
                        <div class="col-sm-3 form-group">
                            <?php
                            FormCommon::TextBox("Đến Ngày", "ToDate", [
                                "value" => $_GET["ToDate"] ?? "",
                                "type" => "date",
                                "class" => "form-control"
                            ])->renderHTML();
                            ?>
                        </div>
                        <div class="col-sm-3 form-group">
                            <?php
                            FormCommon::Select(
                                "Loại phiếu",
                                "Type",
                                [
                                    -1 => "Xuất thuốc",
                                    1 => "Nhập thuốc"
                                ]
                                ,
                                [
                                    "value" => $_GET["Type"] ?? "",
                                    "type" => "date",
                                    "class" => "form-control"
                                ]
                            )->renderHTML();
                            ?>
                        </div>
                        <div class="col-sm-3 form-group">
                            <div class="form-group has-success has-feedback" style="margin-top: 25px;">
                                <button type="submit" style="border-radius: 5px;" class="btn btn-success" name="btnTim"
                                    id="keyword">
                                    <i class="fa fa-filter"></i>&nbsp; Tìm kiếm
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
                <div class=" ">
                    <table class="table table-hover table-bordered ">
                        <tr>
                            <td>#</td>
                            <td>Mã thuốc</td>
                            <td>Tên thuốc</td>
                            <td>Số lần</td>
                        </tr>
                        <?php
                        foreach ($Item as $key => $value) {
                            $thuoc = new SanPham($value["IdThuoc"]);

                            ?>
                            <tr>
                                <td>
                                    <?php echo $key + 1; ?>
                                </td>
                                <td>
                                    <?php
                                    echo $thuoc->Id;
                                    ?>
                                </td>
                                <td>
                                    <?php
                                    echo $thuoc->Name;
                                    ?>
                                </td>
                                <td>
                                    <?php
                                    echo $value["SoLan"];
                                    ?>
                                </td>
                            </tr>
                            <?php
                        }
                        ?>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>