<ol class="breadcrumb">
    <li><a href="/index.php?controller=backend">Home</a></li>
    <li><a href="/index.php?module=quanlythuoc&controller=sanpham&action=index">Danh Sách Thuốc</a></li>
    <li> Quản Lý Thuốc </li>
</ol>

<div class="row ">
    <section class="col-md-3"></section>
    <section class="col-md-6">
        <div class="box box-solid ">
            <div class="box-header ">
                <i class="fa fa-download"></i>
                <h3 class="box-title">Import Thuốc </h3>
                <div class="box-tools">
                    <?php
                    use Module\quanlythuoc\Model\SanPham;
                    // Module\quanlythuoc\Model\btnHtml::btnViewSanPham();
                    ?>
                    <a class="btn btn-warning" target="_self" data-toggle="modal" href='#modal-id'>
                        <i class="fa fa-info" aria-hidden="true"></i>
                    </a>
                    <div class="modal fade" id="modal-id">
                        <div class="modal-dialog modal-lg">
                            <div class="modal-content">
                                <div class="modal-body">
                                    <?php
                                    if (file_exists("public\huongdan\huongdanthemthuoc.html"))
                                        echo file_get_contents("public\huongdan\huongdanthemthuoc.html");
                                    ?>
                                </div>
                                <div class="modal-footer">
                                    <a class="btn btn-success" href="/huongdan/huongdanthuoc/huongdanthemthuoc">Sửa hướng dẫn thêm thuốc</a>
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Đóng lại</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="box-body">
                <table class="table table-bordered">
                    <div class="container_fluit" style="text-align: center;">
                        <a href="/public/excel/FileMauImport.xlsx" style="padding: 10px;display: inline-block; font-size: 16px;" target="dowload">
                            Tải file mẫu
                            <i class="fa fa-download"></i>
                        </a>
                        <form action="" method="post" enctype="multipart/form-data" accept=".xlsx">
                            <label style="background: #aaa;padding: 10px;cursor: pointer;">
                                <br>
                                Chọn file
                                <input type="file" style="visibility: hidden;" name="import_file" />
                            </label>
                            <br>
                            <input type="submit" name="submit" id="import" class="btn btn-success" value="Import File" />

                        </form>
                    </div>
                </table>
            </div>
        </div>
    </section>
</div>