<ol class="breadcrumb">
    <li><a href="/index.php?controller=backend">Home</a></li>
    <li> Quản Lý Thuốc </li>
</ol>

<div class="container-fluid" ng-controller="searchCtrl">
    <form method="get" action="/quanlythuoc/sanpham/index/">
        <div class="form-group d-flex">
            <label class="btn btn-default"><input ng-change="isShowMore(showMore);" ng-model="showMore" style="display: none" type="checkbox"><i class="fa fa-share" aria-hidden="true"></class=></i></label>
            <input id="keyword" class="form-control" name="keyword" value="<?php echo isset($_GET["keyword"]) ? \Model\Common::TextInput($_GET["keyword"]) : "" ?>" type="" placeholder="Nhập Vào Tên Thuốc Hoặc Tên Biệt Dược Để Tìm Kiếm">
            <button class="btn btn-primary no-border-radius" name="btnTim" type="submit">
                <i class="fa fa-search"></i> Tìm Kiếm
            </button>
        </div>
    </form>
    <div class="clearfix">
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title">Danh Sách Thuốc</h3>
                <div class="box-tools">
                    <?php 
                    use Model\Common;
                    use Module\quanlythuoc\Model\SanPham; 
                    Module\quanlythuoc\Model\btnHtml::btnImportSanPham(); 
                    Module\quanlythuoc\Model\btnHtml::btnThemSanPham();
                    ?>
                </div>
            </div>
            <div class="box-body">
                <table class="table table-hover table-bordered">
                    <thead>
                        <tr>
                            <td></td>
                            <th>STT</th>
                            <th>Mã thuốc</th>
                            <th>Tên thuốc</th>
                            <th>Tên biệt dược</th>
                            <th>Số lượng cũ</th>
                            <th>Số lượng mới</th>
                            <th>Tổng</th>
                            <th>Số lượng xuất</th>
                            <th>Số lượng hiện tại</th>
                            <th>Giá nhập</th>
                            <th>Giá bán</th>
                            <!-- <th>Đơn Vị Quy Đổi</th> -->
                            <!-- <th>Công dụng</th> -->
                            <!-- <th>Nhà Sản Xuất</th> -->
                            <!-- <th>Ghi Chú</th> -->
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($items as $index => $item) {
                            $_item = new SanPham($item);
                            // var_dump($_item);
                        ?>
                            <tr>
                                <td style="width: 200px;">
                                    <?php
                                    echo Module\quanlythuoc\Model\btnHtml::btnSuaSanPham($_item->Id);
                                    echo Module\quanlythuoc\Model\btnHtml::btnXoaSanPham($_item->Id);
                                    echo Module\quanlythuoc\Model\btnHtml::btnChiSanPham($_item->Id);
                                    ?>
                                </td>
                                <td><?php echo $index + 1; ?></td>
                                <td><?php echo $_item->Id; ?></td>
                                <td><?php echo $_item->Name; ?></td>
                                <td><?php echo $_item->Namebietduoc; ?></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td class="text-center"><?php echo $_item->Soluong ?></td>
                                <!-- <td><?php echo $_item->CachDungThuoc(); ?></td> -->
                                <!-- <td><?php echo $_item->IdLoaiThuoc()->Name; ?></td> -->
                                <!-- <th><?php echo $_item->DonViQuyDoi(); ?></th> -->
                                <td><?php echo Common::ViewPrice($_item->Gianhap); ?></td>
                                <td><?php echo Common::ViewPrice($_item->Giaban); ?></td>
                                <!-- <td><?php echo $_item->DonViTinh(); ?></td> -->
                                <!-- <td><?php echo Common::ForMatDMY($_item->HSD); ?></td> -->
                                <!-- <th><?php echo $_item->Tacdung; ?></th> -->
                                <!-- <th><?php echo $_item->NhaSX; ?></th> -->
                                <!-- <th><?php echo $_item->Ghichu; ?></th> -->
                            </tr>
                        <?php
                        }
                        ?>
                    </tbody>
                </table>
                <div class="box-footer">
                    <div class="d-flex">
                        <?php
                        \Model\FormCommon::Select(
                            "",
                            "",
                            [10, 20, 50, 100],
                            [
                                "style" => "max-width:150px;",
                                "class" => "form-control",
                                "value" => $pageNumber,
                                "onchange" => "SoDongHienThi(this.value)",
                            ]
                        )->render();
                        ?>
                        <?php
                        $linkPhanTrang = "/index.php?module=quanlythuoc&controller=sanpham&action=index&keyword={$params["keyword"]}&indexPage=[i]&pageNumber={$pageNumber}";
                        echo \Model\Common::PhanTrang($total, $indexPage, $pageNumber, $linkPhanTrang);
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var SoDongHienThi = function(evalue) {
        var linkPhanTrang = '/index.php?module=quanlythuoc&controller=sanpham&action=index&indexPage=1&pageNumber=[j]';
        linkPhanTrang = linkPhanTrang.replace("[j]", evalue);
        window.location.href = linkPhanTrang;
    }
</script>