<ol class="breadcrumb" >
    <li><a href="/index.php?controller=backend" >Home</a></li>
    <li> Quản Lý Thuốc </li>
</ol>  

<div class="container-fluid" >
    <form method="get" action="">
        <div class="form-group d-flex" >  
            <input class="form-control" name="controller" value="quanlyusers" type="hidden"  >
            <input class="form-control" name="action" value="index" type="hidden"  >
            <input class="form-control" name="indexPage" value="<?php

use Module\quanlythuoc\Model\Thuoc;

 echo $indexPage ?>" type="hidden"  >
            <input class="form-control" name="pageNumber" value="<?php echo $pageNumber ?>" type="hidden"  >
            <input class="form-control" name="keyword" value="<?php echo isset($_GET["keyword"]) ? \Model\Common::TextInput($_GET["keyword"]) : "" ?>" type=""  >
            <button class="btn btn-primary" name="btnTim" type="submit"  >Tìm Kiếm</button>
        </div>

    </form>

    <div class="box box-primary" >
        <div class="box-header" >
            <h3 class="box-title" >Danh Sách Thuốc</h3>
            <div class="box-tools" >
                <?php
                echo Thuoc::btnPost()
                ?>
            </div>
        </div>
        <div class="box-body" >
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th></th>
                        <th>Id</th>
                        <th>Thuộc Loại Thuốc</th>
                        <th>Tên Thuốc</th>
                        <th>Tên Biệt Dược</th>
                        <th>Giá Bán</th>
                        <th>Hạn Dùng</th>
                        <th>Nước Sản Xuất</th>
                        <th>Cơ chế tác dụng</th>
                        <th>Ghi Chú</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($DanhSachTaiKhoan as $index => $user) {
                        $_user = new Thuoc($user);
                        ?> 
                        <tr>
                            <th> 

                                <?php
                                echo $_user->btnPut();
                                echo $_user->btnDelete();
                                ?>
                            </th>
                            <th><?php echo $index + 1; ?></th>
                            <th><?php echo $_user->Id; ?></th>
                            <th><?php echo $_user->Idloaithuoc; ?></th>
                            <th><?php echo $_user->Name; ?></th>
                        </tr>
                        <?php
                    }
                    ?> 
                </tbody>
            </table>    

        </div>
        <div class="box-footer" >
            <div  class="d-flex"> 
                <?php
                \Model\FormCommon::Select("", "", [10, 20, 50, 100],
                        [
                            "style" => "max-width:150px;",
                            "class" => "form-control",
                            "value" => $pageNumber,
                            "onchange" => "SoDongHienThi(this.value)",
                        ]
                )->render();
                ?> 
                <?php
                $linkPhanTrang = "/index.php?controller=quanlyusers&action=index&indexPage=[i]&pageNumber={$pageNumber}";
                echo \Model\Common::PhanTrang($total, $indexPage, $pageNumber, $linkPhanTrang);
                ?> 
            </div>
        </div>
    </div>    
</div>
<script type="text/javascript" >
    var SoDongHienThi = function (evalue) {
        var linkPhanTrang = '/index.php?controller=quanlyusers&action=index&indexPage=1&pageNumber=[j]';
        linkPhanTrang = linkPhanTrang.replace("[j]", evalue);
        window.location.href = linkPhanTrang;
    }
</script>


