<ol class="breadcrumb">
    <li><a href="/index.php?controller=backend">Home</a></li>
    <li> Danh Sách Thuốc Trong Kho </li>
</ol>

<div class="container-fluid" ng-controller="searchCtrl">
    <form method="get" action="/quanlythuoc/sanpham/index/">
        <div class="form-group d-flex">
            <label class="btn btn-default">
                <input ng-change="isShowMore(showMore);" ng-model="showMore" style="display: none" type="checkbox">
                <i class="fa fa-bars" aria-hidden="true"></i>
            </label>
            <input id="keyword" class="form-control" name="keyword" value="<?php echo isset($_GET["keyword"]) ? \Model\Common::TextInput($_GET["keyword"]) : "" ?>" type="" placeholder="Nhập vào tên thuốc để tìm kiếm">
            <button class="btn btn-primary no-border-radius" name="btnTim" type="submit">
                <i class="fa fa-search"></i> Tìm Kiếm
            </button>
        </div>
    </form>
    <div class="clearfix">
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title">Danh Sách Thuốc</h3>
                <div class="box-tools">
                    <?php

                    use Model\Common;
                    use Model\FormRender;
                    use Module\quanlythuoc\Model\SanPham;
                    Module\quanlythuoc\Model\btnHtml::btnDongBoSL();
                    Module\quanlythuoc\Model\btnHtml::btnImportSanPham();
                    Module\quanlythuoc\Model\btnHtml::btnExportSanPham();
                    Module\quanlythuoc\Model\btnHtml::btnThemSanPham();
                    \Model\FormRender::HuongDan("danhsachthuoc", "Hướng dẫn thuốc")
                    ?>
                </div>
            </div>
            <div class="box-body">
                <table class="table table-hover table-bordered">
                    <thead>
                        <tr>
                            <th>Thao Tác</th>
                            <th class="text-center">STT
                                <p style="margin-bottom: 0px;" class="text-center">(1)</p>
                            </th>
                            <th class="text-center">Mã thuốc
                                <p style="margin-bottom: 0px;" class="text-center">(2)</p>
                            </th>
                            <th class="text-center">Tên thuốc
                                <p style="margin-bottom: 0px;" class="text-center">(2)</p>
                            </th>
                            <th class="text-center">Tổng Nhập
                                <p style="margin-bottom: 0px;" class="text-center">(3)</p>
                            </th>
                            <th class="text-center">Tổng Xuất
                                <p style="margin-bottom: 0px;" class="text-center">(4)</p>
                            </th>
                            <th class="text-center">SL
                                <?php echo FormRender::ToolTipElement("Số Lượng Ban Đầu Không Có Phiếu Nhập") ?>
                                <p style="margin-bottom: 0px;"v class="text-center">(5)</p>
                            </th>
                            <th class="text-center">Tồn Kho
                                <p style="margin-bottom: 0px;" class="text-center">(6)=(5)-(4)+(3)</p>
                            </th>
                            <th class="text-center">Giá nhập
                                <p style="margin-bottom: 0px;" class="text-center">(7)</p>
                            </th>
                            <th class="text-center">Giá bán
                                <p style="margin-bottom: 0px;" class="text-center">(8)</p>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($items as $index => $item) {
                            $_item = new SanPham($item);
                            // var_dump($_item);
                        ?>
                            <tr>
                                <td style="width: 150px;">
                                    <div class="btn-tools">
                                        <?php
                                        echo Module\quanlythuoc\Model\btnHtml::btnSuaSanPham($_item->Id);
                                        echo Module\quanlythuoc\Model\btnHtml::btnXoaSanPham($_item->Id);
                                        echo Module\quanlythuoc\Model\btnHtml::btnChiTietSanPham($_item->Id);
                                        ?>
                                    </div>

                                </td>
                                <td><?php echo (($indexPage - 1) * $pageNumber) + $index + 1; ?></td>
                                <td><?php echo $_item->Id; ?></td>
                                <td><?php echo $_item->Name; ?></td>
                                <td><?php echo $_item->SLNhap; ?></td>
                                <td><?php echo $_item->SLXuat; ?></td>
                                <td><?php echo $_item->Soluong; ?></td>
                                <td><?php echo $_item->SLHienTai; ?></td>
                                <!-- <td><?php echo $_item->CachDungThuoc(); ?></td> -->
                                <!-- <td><?php echo $_item->IdLoaiThuoc()->Name; ?></td> -->
                                <!-- <th><?php echo $_item->DonViQuyDoi(); ?></th> -->
                                <td><?php echo Common::ViewPrice($_item->Gianhap); ?></td>
                                <td><?php echo Common::ViewPrice($_item->Giaban); ?></td>
                            </tr>
                        <?php
                        }
                        ?>
                    </tbody>
                </table>
                <div class="box-footer">
                    <div class="d-flex">
                        <?php
                        \Model\FormCommon::Select(
                            "",
                            "",
                            [10, 20, 50, 100],
                            [
                                "style" => "max-width:150px;",
                                "class" => "form-control",
                                "value" => $pageNumber,
                                "onchange" => "SoDongHienThi(this.value)",
                            ]
                        )->render();
                        ?>
                        <?php
                        $linkPhanTrang = "/index.php?module=quanlythuoc&controller=sanpham&action=index&keyword={$params["keyword"]}&indexPage=[i]&pageNumber={$pageNumber}";
                        echo \Model\Common::PhanTrang($total, $indexPage, $pageNumber, $linkPhanTrang);
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<script type="text/javascript">
    var SoDongHienThi = function(evalue) {
        var linkPhanTrang = '/index.php?module=quanlythuoc&controller=sanpham&action=index&indexPage=1&pageNumber=[j]';
        linkPhanTrang = linkPhanTrang.replace("[j]", evalue);
        window.location.href = linkPhanTrang;
    }
</script>