<ol class="breadcrumb">
    <li><a href="/backend">Home</a></li>
    <li><a href="/quanlythuoc/sanpham/index"> Danh Sách Thuốc</a></li>
    <li> Thêm Thuốc Mới </li>
</ol>
<?php

use Model\FormRender;
use Module\quanlythuoc\Model\SanPham;

$roleDetail = new Model\Role();
?>
<div class="container-fluid">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Thêm Thuốc Mới</h3>
            <div class="box-tools">
                <!-- <?php
                Module\quanlythuoc\Model\btnHtml::btnViewSanPham();
                ?> -->
                <?php
                \Model\FormRender::HuongDan("themthuoc", "Hướng dẫn thêm thuốc")
                    ?>
            </div>
        </div>
        <!-- <div class="box-body"> -->
        <form action="" method="post" enctype="multipart/form-data">
            <div class="box-body">
                <?php
                $sp = new \Module\quanlythuoc\Model\SanPham\FormSanPham();
                ?>
                <div class="">
                    <div class="col-md-3">
                        <?php $sp->Id(SanPham::CreatId())->renderHtml(); ?>
                    </div>
                    <div class="col-md-3">
                        <?php $sp->Name()->renderHtml(); ?>
                    </div>
                    <!-- <div class="col-md-3">
                        <?php $sp->Namebietduoc()->renderHtml(); ?>
                    </div> -->
                    <div class="col-md-3">
                        <?php $sp->Idloaithuoc("DMT-002")->renderHtml(); ?>
                    </div>
                    <div class="col-md-3">
                        <?php $sp->CachDung()->renderHtml(); ?>
                    </div>
                    <div class="col-md-3">
                        <?php $sp->Soluong(0)->renderHtml(); ?>
                    </div>
                    <div class="col-md-3">
                        <?php $sp->NhaSX()->renderHtml(); ?>
                    </div>
                    <div class="col-md-3">
                        <?php $sp->NuocSX()->renderHtml(); ?>
                    </div>
                    <div class="col-md-3">
                        <?php $sp->Solo()->renderHtml(); ?>
                    </div>
                    <div class="col-md-3">
                        <?php $sp->Gianhap(0)->renderHtml(); ?>
                    </div>
                    <div class="col-md-3">
                        <?php $sp->Giaban()->renderHtml(); ?>
                    </div>
                    <div class="col-md-3">
                        <?php $sp->DVQuyDoi()->renderHtml(); ?>
                    </div>
                    <div class="col-md-3">
                        <?php $sp->DVT()->renderHtml(); ?>
                    </div>
                    <div class="col-md-12">
                        <?php $sp->Canhbao(100)->renderHtml(); ?>
                    </div>
                    <div class="col-md-4">
                        <?php $sp->Tacdung()->renderHtml(); ?>
                    </div>
                    <div class="col-md-4">
                        <?php $sp->Cochetacdung()->renderHtml(); ?>
                    </div>
                    <div class="col-md-4">
                        <?php $sp->Ghichu()->renderHtml(); ?>
                    </div>
                    <div class="col-md-12 ">
                        <button class="btn btn-warning" type="reset">Làm Lại</button>
                        <!-- <button class="btn btn-success">Lưu</button> -->
                        <button class="btn btn-success" name="LuuThoat">Thêm Mới</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>