<?php

use Module\cart\Model\Order;
use PhpOffice\PhpSpreadsheet\Calculation\DateTimeExcel\Days;
use Model\Products;
use Module\donthuoc\Model\DonThuoc;
use Module\quanlythuoc\Model\SanPham;
use Module\benhnhan\Model\BenhNhan;
use Model\Common;
use PhpOffice\PhpSpreadsheet\Calculation\MathTrig\Sum;
use Module\donthuoc\Model\DonThuocDetail;
use Module\donthuoc\Permission;

?>
<style>
    @media print {

        .no-print,
        .no-print * {
            display: none !important;
        }
    }

    .main {
        margin: 0;
        padding: 0;
    }

    .salesslip {
        width: 500px;
        margin: auto;
    }

    .shop {
        text-align: center;
    }

    /* ------------------------------ */
    .temporary {
        margin: 0 25px;
        display: flex;
        justify-content: space-around;
        margin-bottom: 15px;
    }

    td.temporary-title {
        padding-right: 7px;
    }

    /* ------------------------------ */
    .content {
        display: flex;
        justify-content: center;
        align-items: flex-start;
        min-height: unset;
    }

    /* ------------------------------ */
    .total-order {
        display: flex;
        flex-basis: 50%;
        justify-content: space-between;
        margin-top: 10px;
    }

    .total-order p {
        font-size: 17px;
        margin: 5px 0;
    }

    /* ------------------------------ */
    .footer {
        text-align: center;
    }

    .btn {
        margin-left: 50%;
        padding: 5px 30px;
        transform: translateX(-50%);
        border-radius: 10px;
        border: 1px solid #9e9e9e;
        margin-bottom: 10px;
    }

    .btn:hover {
        color: #000;
        cursor: pointer;
        background-color: #6b6565ba;
    }
</style>
<?php
$donthuoc = new DonThuoc($_GET["id"]);
$IdDonThuoc = $donthuoc->Id;

?>
<div class="box box-default" style="border: none;">
    <div class="main main-body">
        <div class="salesslip">
            <div class="shop">
                <h4 style="margin: 0px; margin-top:5px;font-size:16px"><b>PHÒNG KHÁM DEMO</b></h4>
                <span style="font-size: 11px;">ĐC: 115/21 Phạm đình hổ, P6, Q6 . Giờ làm việc: Sáng 7h30 -
                    11h, Chiều 17h - 20h30 (Nghỉ thứ 7)
                </span>
                <p style="margin-bottom: 0px;">
                <h1 style="font-size: 22px !important;margin:0px;margin-bottom: 15px;font-weight:bold;">ĐƠN THUỐC</h1>
                </p>
            </div>
            <!---------------------------------->
            <div style="margin: 0; border-bottom: 0px solid #00000042">
                <table class="table-hover" style="width: 100%;">
                    <thead>
                        <tr>
                            <td><b>Họ và tên</b> :
                                <?php echo $donthuoc->NameBN; ?></b>
                            </td>
                            <td><b>Năm sinh </b>:
                                <?php echo date('Y', strtotime($donthuoc->NgaySinh)); ?>
                            </td>
                            <td><b>Giới</b>:
                                <?php echo $donthuoc->GioiTinh(); ?>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="2"><b>Địa chỉ</b> :
                                <?php echo DonThuoc::GetItemById('Address', $donthuoc->IdBenhNhan); ?>
                            </td>
                            <td> <b>SĐT </b>:
                                <?php echo DonThuoc::GetItemById('Phone', $donthuoc->IdBenhNhan); ?>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="3"><b>Chẩn đoán </b>:
                                <?php echo $donthuoc->ChanDoanBenh; ?>
                            </td>
                        </tr>
                    </thead>
                </table>
            </div>

            <div style="margin: 0; border-bottom: 1px solid #00000042">
                <table style="width: 100%;">
                    <thead>
                        <tr style="border-bottom: 1px solid #00000042;">
                            <th class="text-center">STT</th>
                            <th style="padding-left: 10px;" class="text-left">Tên thuốc</th>
                            <th class="text-center" style="padding-right: 10px;">Số lượng</th>

                            <th>
                                <?php
                                echo $donthuoc->ThuocLoaiDon != 2 ? "Thành Tiền" : "";
                                ?>
                            </th>

                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $detail = DonThuoc::GetDetailById($IdDonThuoc);
                        $common = new Common();
                        // var_dump($detail);
                        $sum = 0;
                        foreach ($detail as $index => $DTdetail) { ?>
                            <tr>
                                <td class="text-center">
                                    <b>
                                        <?php echo $index + 1 ?>
                                    </b>
                                </td>
                                <th style="white-space: nowrap;padding-left:10px;">
                                    <?php echo SanPham::GetNameById($DTdetail['IdThuoc']); ?>
                                </th>
                                <td class="text-center"><span style="white-space: nowrap; font-weight: 400 !important;">
                                        <b>
                                            <?php echo $DTdetail['SoLuong'] . '</b> ' . $DTdetail['DVT']; ?>
                                    </span>
                                </td>

                                <td style="white-space: nowrap;">
                                    <?php
                                    if ($donthuoc->ThuocLoaiDon != 2) {
                                        echo Common::ViewPrice($DTdetail['SoLuong'] * $DTdetail['GiaBan']);
                                    }
                                    ?>
                                </td>

                                <td>
                                    <?php
                                    if ($donthuoc->ThuocLoaiDon != 2) {
                                        $sum += $DTdetail['SoLuong'] * $DTdetail['GiaBan'];
                                    }
                                    ?>
                                </td>
                            </tr>
                            <tr>
                                <td></td>
                                <?php
                                if ($DTdetail['GhiChu']) { ?>
                                    <td class="text-center">
                                        <i>
                                            <?php
                                            if ($DTdetail['GhiChu']) {
                                                echo '(' . $DTdetail['GhiChu'] . ')';
                                            }
                                            ?>
                                        </i>
                                    </td>
                                    <?php
                                }
                                ?>

                            </tr>
                            <tr>
                                <td colspan="4">
                                    <table width="100%">
                                        <tr style="border-bottom: 0px solid #00000042;">
                                            <td width="1" style="padding-left: 25px;"></td>
                                            <td width="2" style="width:80px;padding-left: 22px;"><i>Sáng: </i>

                                                <?php if ($DTdetail['Sang'] > 0)
                                                    echo SanPham::GetDesByVal($DTdetail['Sang'], 'donviquydoi') . ' ' . $DTdetail['DVT']; ?>


                                            </td>
                                            <td width="2" style="width:80px;"><i>Trưa:</i>
                                                <?php if ($DTdetail['Trua'] > 0)
                                                    echo SanPham::GetDesByVal($DTdetail['Trua'], 'donviquydoi') . ' ' . $DTdetail['DVT'] ?? ""; ?>
                                            </td>
                                            <td width="2" style="width:80px;"><i>Tối:</i>
                                                <?php if ($DTdetail['Chieu'] > 0)
                                                    echo SanPham::GetDesByVal($DTdetail['Chieu'], 'donviquydoi') . ' ' . $DTdetail['DVT'] ?? "" ?>
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>

                            <?php
                        }
                        ?>
                    </tbody>

                </table>
            </div>
            <tr>
                <td>

                    <b>Tổng cộng :</b><span style="float : right; font-weight: bold;">
                        <?php echo Common::ViewPrice($sum) . " " . "( " . $common->convert_number_to_words($sum) . " )" ?>
                    </span>
                    <p>
                        Số khoản : <b>
                            <?php echo count($detail); ?>
                        </b>
                    </p>
                </td>
            </tr>
            <div class="row">
                <div class="col-xs-6"></div>
                <div class="col-xs-6 text-center">
                    <h6
                        style=" font-weight: 500; margin: 10px 0;<?php echo $donthuoc->ThuocLoaiDon != 2 ? "margin-top: -20px" : "" ?> ">
                        <i>
                            <?php $date = getdate();
                            // echo $date['weekday'] . ", ";
                            echo "Ngày " . $date['mday'] . " ";
                            echo "Tháng " . $date['mon'] . " ";
                            echo "Năm " . $date['year'] . "";
                            ?>
                        </i>
                    </h6>
                    <h6>Bác Sỹ</h6><br><br>
                    Nguyễn Văn A
                </div>
            </div>
        </div>
    </div>
</div>