<style>
    .form-group {
        margin-bottom: 0px !important;
    }

    .form-control {
        height: 34px !important;
    }
</style>
<ol class="breadcrumb">
    <li><a href="/index.php?controller=backend">Home</a></li>
    <li><a href="/index.php?module=donthuoc&controller=index&action=index"> Danh Sách Đơn Thuốc</a></li>
    <li> Sao Chép Đơn Thuốc </li>
</ol>
<?php

use Module\benhnhan\Model\BenhNhan;
use Module\benhnhan\Model\BenhNhan\FormBenhNhan;
use Module\donthuoc\Model\btnHtml;
use Module\donthuoc\Model\DonThuoc;
use Module\donthuoc\Model\DonThuoc\FormDonThuoc;
use Module\donthuoc\Model\DonThuocDetail;
use Module\quanlythuoc\Model\SanPham;

$roleDetail = new Model\Role();
$form = new FormDonThuoc();
$bn = new FormBenhNhan();
$donthuoc = new DonThuoc($donthuoc);
// var_dump($donthuoc);
// lấy thông tin bệnh nhân cũ

$benhnhan = new BenhNhan($donthuoc->IdBenhNhan);
if (isset($_GET["isnewbn"])) {
    $benhnhan = new BenhNhan();
}


// echo $benhnhan->Ngaysinh;
// echo $a = substr($benhnhan->Ngaysinh,5,2)
?>
<div class="container-fluid">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Sao Chép Đơn Thuốc</h3>
            <div class="box-tools">
                <div class="box-tools">
                    <?php
                    \Model\FormRender::HuongDan("copydonthuoc", "Hướng dẫn copy đơn thuốc");
                    ?>
                </div>
            </div>
        </div>
        <div class="box-body">
            <form action="" method="post" id="formKhachHang" enctype="multipart/form-data">
                <div class="col-md-4">
                    <div class="row">
                        <fieldset style="min-height: 400px;">
                            <legend>Thông tin đơn thuốc</legend>
                            <?php
                            $form = new FormDonThuoc();
                            ?>
                            <div class="col-md-12">
                                <label>Ngày Dùng Thuốc</label>
                                <div class="d-flex">
                                    <?php echo $form->TongNgayDung($_SESSION["SoNgaySDThuoc"] ?? 0)->render(); ?>
                                    <?php btnHtml::btnCapNhatNgayDung(); ?>
                                </div>

                            </div>
                            <div class="col-md-12">
                                <?php echo $form->ThuocLoaiDon($donthuoc->ThuocLoaiDon)->renderHTML(); ?>
                            </div>
                            <div class="col-md-12">
                                <?php echo $form->ChanDoanBenh($donthuoc->ChanDoanBenh)->renderHTML(); ?>
                            </div>
                            <div class="col-md-12">
                                <?php echo $form->Id($donthuoc->Id)->renderHTML(); ?>
                            </div>
                            <div class="col-md-12">
                                <?php echo $form->ThoiGianKham($donthuoc->ThoiGianKham)->renderHTML(); ?>
                            </div>
                        </fieldset>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="row">
                        <fieldset style="min-height: 400px;">
                            <legend>Thông tin bệnh nhân</legend>
                            <div class="col-md-6">
                                <?php $bn->IdValue($benhnhan->Id)->render(); ?>
                                <?php $bn->Name($benhnhan->Name, null)->renderHtml(); ?>
                            </div>
                            <div class="col-md-6">
                                <?php $bn->Phone($benhnhan->Phone, null)->renderHtml(); ?>
                            </div>
                            <div class="col-md-6">
                                <?php $bn->CMND($benhnhan->CMND)->renderHtml(); ?>
                            </div>
                            <div class="col-md-6">
                                <?php $bn->Gioitinh($benhnhan->Gioitinh)->renderHtml(); ?>
                            </div>
                            <div class="col-md-4">
                                <?php $bn->Namsinh(substr($benhnhan->Ngaysinh, 0, 4))->renderHtml(); ?>
                            </div>
                            <div class="col-md-4">
                                <?php $bn->Thangsinh(substr($benhnhan->Ngaysinh, 5, 2))->renderHtml(); ?>
                            </div>
                            <div class="col-md-4">
                                <?php $bn->Ngaysinh(substr($benhnhan->Ngaysinh, 8, 2))->renderHtml(); ?>
                            </div>
                            <div class="col-md-12">
                                <?php $bn->Address($benhnhan->Address)->renderHtml(); ?>
                            </div>
                            <div class="col-md-4 form-group">
                                <?php $bn->TinhThanh($benhnhan->TinhThanh, "TinhThanhBenhNhan", "#QuanHuyenBenhNhan")->renderHtml(); ?>
                            </div>
                            <div class="col-md-4 form-group">
                                <?php $bn->QuanHuyen($benhnhan->QuanHuyen, "QuanHuyenBenhNhan", "#PhuongXaBenhNhan")->renderHtml(); ?>
                            </div>
                            <div class="col-md-4 form-group">
                                <?php $bn->PhuongXa($benhnhan->PhuongXa, "PhuongXaBenhNhan")->renderHtml(); ?>
                            </div>
                        </fieldset>
                    </div>
                </div>
                <fieldset>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>
                                    <button data-toggle="tooltip" data-placement="top" title="Thêm thuốc mới"
                                        type="button" class="btn btn-success" id="btn-add">
                                        <i class="fa fa-plus" aria-hidden="true"></i>
                                    </button>
                                </th>
                                <th>STT</th>
                                <th>Tên Thuốc</th>
                                <th>Số Ngày Dùng</th>
                                <th>Cách Dùng</th>
                                <th>Đơn Vị Tính</th>
                                <th>Sáng</th>
                                <th>Trưa</th>
                                <th>Tối</th>
                                <th>Số Lượng</th>
                                <th>Ghi Chú</th>
                            </tr>
                        </thead>
                        <tbody class="table-thuoc">
                            <?php
                            // var_dump(DonThuocDetail::DsThuoc());
                            $i = 0;
                            foreach (DonThuocDetail::DsThuoc() as $mathuoc => $thuoc) {
                                $sanPham = new SanPham($thuoc["Id"] ?? null);
                                ?>
                                <tr>
                                    <th>
                                        <button data-toggle="tooltip" data-placement="top" title="Xóa thuốc" type="button"
                                            title="Xóa thuốc này?" class="btn  btn-danger deleterows"
                                            id="<?php echo 'delete' . $mathuoc ?>" index=<?php echo $mathuoc ?>>
                                            <i class="fa fa-minus" aria-hidden="true"></i>
                                        </button>
                                    </th>
                                    <td style="display: table-cell; vertical-align: middle;">
                                        <div class="text-center">
                                            <?php echo $i + 1; ?>
                                        </div>
                                    </td>
                                    <td style="width:250px;">
                                        <?php
                                        echo $form->Name($thuoc["Id"] ?? "", "donthuoc" . $i, $i)->renderHTML() ?>
                                    </td>
                                    <td style="width:120px;">
                                        <?php echo $form->SoNgaySDThuoc($thuoc["SoNgaySDThuoc"] ?? "", "SoNgaySD" . $i, $i)->render(); ?>
                                    </td>
                                    <td style="width: 150px;">
                                        <?php echo $form->CachDung($sanPham->CachDungThuoc(), "cachdungthuoc" . $i, $i)->render(); ?>
                                    </td>
                                    <td style="width: 100px;">
                                        <?php echo $form->DVT($sanPham->DonViTinh(), "dvt" . $i, $i)->render(); ?>
                                    </td>
                                    <td style="width: 100px;">
                                        <?php echo $form->Sang($thuoc["Sang"] ?? "", "sang" . $i, $i)->render(); ?>
                                    </td>
                                    <td style="width: 100px;">
                                        <?php echo $form->Trua($thuoc["Trua"] ?? "", "trua" . $i, $i)->render(); ?>
                                    </td>
                                    <td style="width: 100px;">
                                        <?php echo $form->Chieu($thuoc["Chieu"] ?? "", "chieu" . $i, $i)->render(); ?>
                                    </td>
                                    <td>
                                        <?php echo $form->SoLuong($thuoc["Soluong"] ?? "", "soluong" . $i, $i)->render(); ?>
                                    </td>
                                    <td>
                                        <?php echo $form->GhiChu($sanPham->Ghichu, "ghichu" . $i, $i)->render(); ?>
                                    </td>
                                </tr>
                                <?php
                                $i++;
                            }
                            ?>
                        </tbody>
                    </table>
                    <div class="col-md-12 ">
                        <button class="btn btn-warning" type="reset">Làm Lại</button>
                        <button class="btn btn-primary" name="LuuThoat">Sao chép đơn thuốc</button>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>
<script src="/public/TinhThanh/tinhthanh.js"></script>
<script src="/Module/donthuoc/public/postdonthuoc.js"></script>