<ol class="breadcrumb">
    <li><a href="/index.php?controller=backend">Home</a></li>
    <li><a href="/index.php?module=donthuoc&controller=index&action=index">Danh Sách Đơn Thuốc</a></li>
    <li> Quản Lý Đơn Thuốc </li>
</ol>

<div class="container-fluid">
    <form method="get" action="/donthuoc/index/index/">
        <div class="form-group d-flex">
            <label class="btn btn-default"><input ng-change="isShowMore(showMore);" ng-model="showMore" style="display: none" type="checkbox"><i class="fa fa-share" aria-hidden="true"></class=></i></label>
            <input id="keyword" class="form-control" name="keyword" value="<?php echo isset($_GET["keyword"]) ? \Model\Common::TextInput($_GET["keyword"]) : "" ?>" type="" placeholder="Nhập mã đơn thuốc hoặc tên bệnh nhân để tìm kiếm">
            <button class="btn btn-primary no-border-radius" name="btnTim" type="submit">
                <i class="fa fa-search"></i> Tìm Kiếm
            </button>
        </div>
    </form>
    <div class="clearfix">
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title">Danh Sách Đơn Thuốc</h3>
                <div class="box-tools">
                    <?php

                    use Model\Common;
                    use Model\Locations;
                    use Model\OptionsService;
                    use Model\TinhThanh;
                    use Module\donthuoc\Model\DonThuoc;

                    Module\donthuoc\Model\btnHtml::btnThemDonThuoc();
                    ?>

                    <a class="btn btn-primary" data-toggle="modal" href='#modal-id'>Hướng dẫn</a>
                    <div class="modal fade" id="modal-id">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-body">
                                    <?php
                                    $link = 'huongdansudung';
                                    $path = "public/huongdan/{$link}.html";
                                    echo file_get_contents($path);
                                    ?>
                                </div>
                                <div class="modal-footer">
                                    <a href="<?php echo "/huongdan/put/?link=$link"?>" type="button" class="btn btn-success">Sửa File</a>
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Đóng lại</button>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <div class="box-body">
                <table class="table table-hover table-bordered">
                    <thead>
                        <tr>
                            <th></th>
                            <th>STT</th>
                            <th>Mã Đơn Thuốc</th>
                            <!-- <th>Mã Bệnh Nhân</th> -->
                            <th>Tên Bệnh Nhân</th>
                            <th>Giới Tính</th>
                            <th>Ngày Sinh</th>
                            <th>Thời Gian Khám Bệnh</th>
                            <th>Chẩn Đoán</th>
                            <th>Thuộc Loại Đơn</th>
                            <th>Ngày Dùng</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        // var_dump($items);
                        // echo $a;
                        foreach ($items as $index => $item) {
                            $_item = new DonThuoc($item);
                            $nameBN = $_item->GetNameById($_item->IdBenhNhan);
                            // var_dump($_item);
                        ?>
                            <tr>
                                <td style="width: 250px;">
                                    <?php
                                    echo Module\donthuoc\Model\btnHtml::btnSuaDonThuoc($_item->Id);
                                    echo Module\donthuoc\Model\btnHtml::btnCopyDonThuoc($_item->Id);
                                    echo Module\donthuoc\Model\btnHtml::btnXoaDonThuoc($_item->Id);
                                    echo Module\donthuoc\Model\btnHtml::btnchitiet($_item->Id);
                                    ?>
                                </td>
                                <td><?php echo $index + 1; ?></td>
                                <td><?php echo $_item->Id; ?></td>
                                <!-- <td><?php echo $_item->IdBenhNhan; ?></td> -->
                                <td><?php echo $nameBN; ?></td>
                                <td><?php echo $_item->Gioitinh(); ?></td>
                                <td><?php echo $_item->NgaySinh; ?></td>
                                <td><?php echo date("d-m-Y H:i:s", strtotime($_item->ThoiGianKham)); ?></td>
                                <td><?php echo $_item->ChanDoanBenh ?></td>
                                <td><?php echo $_item->ThuocLoaiDon() ?></td>
                                <td><?php echo $_item->TongNgayDung; ?></td>

                            </tr>
                        <?php
                        }
                        ?>
                    </tbody>
                </table>
                <div class="box-footer">
                    <div class="d-flex">
                        <?php
                        \Model\FormCommon::Select(
                            "",
                            "",
                            [10, 20, 50, 100],
                            [
                                "style" => "max-width:150px;",
                                "class" => "form-control",
                                "value" => $pageNumber,
                                "onchange" => "SoDongHienThi(this.value)",
                            ]
                        )->render();
                        ?>
                        <?php
                        $linkPhanTrang = "/index.php?module=donthuoc&controller=index&action=index&keyword={$params["keyword"]}&indexPage=[i]&pageNumber={$pageNumber}";
                        echo \Model\Common::PhanTrang($total, $indexPage, $pageNumber, $linkPhanTrang);
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var SoDongHienThi = function(evalue) {
        var linkPhanTrang = '/index.php?module=donthuoc&controller=index&action=index&indexPage=1&pageNumber=[j]';
        linkPhanTrang = linkPhanTrang.replace("[j]", evalue);
        window.location.href = linkPhanTrang;
    }
</script>