<?php

use Model\Common;
use Model\FormRender;
use Model\Locations;
use Model\OptionsService;
use Model\TinhThanh;
use Module\donthuoc\Model\DonThuoc;
?>
<ol class="breadcrumb">
    <li><a href="/index.php?controller=backend">Home</a></li>
    <li class="active"> Danh Sách Đơn Thuốc </li>
</ol>

<div class="container-fluid">


    


    <form method="get" action="/donthuoc/index/index/">
        <div class="form-group d-flex">
            <label class="btn btn-default"><input ng-change="isShowMore(showMore);" ng-model="showMore" style="display: none" type="checkbox"><i class="fa fa-share" aria-hidden="true"></class=></i></label>
            <input id="keyword" class="form-control" name="keyword" value="<?php echo isset($_GET["keyword"]) ? \Model\Common::TextInput($_GET["keyword"]) : "" ?>" type="" placeholder="Nhập mã đơn thuốc hoặc tên bệnh nhân để tìm kiếm">
            <button class="btn btn-primary no-border-radius" name="btnTim" type="submit">
                <i class="fa fa-search"></i> Tìm Kiếm
            </button>
        </div>
    </form>
    <div class="clearfix">
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title">Danh Sách Đơn Thuốc</h3>
                <div class="box-tools">
                    <!-- <a type="button" href="/thongke/donthuoctrongngay" class="btn btn-success"><i class="fa fa-list"></i>&nbsp;Danh sách đơn thuốc trong ngày</a> -->
                    <?php
                    Module\donthuoc\Model\btnHtml::btnThemDonThuoc();
                    \Model\FormRender::HuongDan("danhsachdonthuoc", "Hướng dẫn đơn thuốc");
                    ?>
                </div>
            </div>
            <div class="box-body">
                <table class="table table-hover table-bordered">
                    <thead>
                        <tr>
                            <th></th>
                            <th class="text-center">STT</th>
                            <th>Mã Đơn Thuốc</th>
                            <th>Tên Bệnh Nhân</th>
                            <th>Giới Tính</th>
                            <th>Ngày Sinh</th>
                            <th>Thời Gian Khám Bệnh</th>
                            <th>Chẩn Đoán</th>
                            <!-- <th>Ngày Dùng</th> -->
                            <th>Tình trạng</th>
                            <th>Thuộc Loại Đơn</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($items as $index => $item) {
                            $_item = new DonThuoc($item);
                        ?>
                            <tr>
                                <td class="text-center">
                                    <?php
                                    echo Module\donthuoc\Model\btnHtml::btnCopyDonThuoc($_item->Id);
                                    // echo Module\donthuoc\Model\btnHtml::btnXoaDonThuoc($_item->Id);
                                    echo Module\donthuoc\Model\btnHtml::btnSuaDonThuoc($_item->Id);
                                    echo Module\donthuoc\Model\btnHtml::btnchitiet($_item->Id);
                                    ?>
                                </td>
                                <td class="text-center"><?php echo (($indexPage - 1) * $pageNumber) + $index + 1; ?></td>
                                <td><?php echo $_item->Id; ?></td>
                                <td><?php echo $_item->BenhNhan()->Name; ?></td>
                                <td><?php echo $_item->BenhNhan()->Gioitinh(); ?></td>
                                <td><?php echo Common::ForMatDMY($_item->BenhNhan()->Ngaysinh); ?></td>
                                <td><?php echo date("d-m-Y H:i:s", strtotime($_item->ThoiGianKham)); ?></td>
                                <td><?php echo $_item->ChanDoanBenh ?></td>
                                <!-- <td><?php echo $_item->TongNgayDung; ?></td> -->
                                <td><?php echo $_item->Status(); ?></td>
                                <td><?php echo $_item->ThuocLoaiDon() ?></td>
                            </tr>
                        <?php
                        }
                        ?>
                    </tbody>
                </table>
                <div class="box-footer">
                    <div class="d-flex">
                        <?php
                        \Model\FormCommon::Select(
                            "",
                            "",
                            [10, 20, 50, 100],
                            [
                                "style" => "max-width:150px;",
                                "class" => "form-control",
                                "value" => $pageNumber,
                                "onchange" => "SoDongHienThi(this.value)",
                            ]
                        )->render();
                        ?>
                        <?php
                        $linkPhanTrang = "/index.php?module=donthuoc&controller=index&action=index&keyword={$params["keyword"]}&indexPage=[i]&pageNumber={$pageNumber}";
                        echo \Model\Common::PhanTrang($total, $indexPage, $pageNumber, $linkPhanTrang);
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var SoDongHienThi = function(evalue) {
        var linkPhanTrang = '/index.php?module=donthuoc&controller=index&action=index&indexPage=1&pageNumber=[j]';
        linkPhanTrang = linkPhanTrang.replace("[j]", evalue);
        window.location.href = linkPhanTrang;
    }
</script>