<style>
    .form-group {
        margin-bottom: 0px !important;
    }

    .form-control {
        height: 34px !important;
    }
</style>
<ol class="breadcrumb">
    <li><a href="/index.php?controller=backend">Home</a></li>
    <li><a href="/index.php?module=donthuoc&controller=index&action=index"> Danh Sách Toa Thuốc</a></li>
    <li> Thêm Toa Thuốc </li>
</ol>
<?php

use Model\FormRender;
use Module\benhnhan\Model\BenhNhan;
use Module\benhnhan\Model\BenhNhan\FormBenhNhan;
use Module\donthuoc\Model\btnHtml;
use Module\donthuoc\Model\DonThuoc\FormDonThuoc;
use Module\donthuoc\Model\DonThuocDetail;
use Module\quanlythuoc\Model\SanPham;
use Module\donthuoc\Model\DonThuoc;

$roleDetail = new Model\Role();

?>
<div class="container-fluid">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Thêm Toa Thuốc</h3>
            <div class="box-tools">
                <?php
                \Model\FormRender::HuongDan("themdonthuoc", "Hướng dẫn thêm đơn thuốc");
                ?>
            </div>
        </div>
        <div class="box-body">
            <form action="" method="post" id="formKhachHang" enctype="multipart/form-data">
                <?php
                $bn = new FormBenhNhan();
                $benhnhan = new BenhNhan();
                ?>
                <div class="col-md-4">
                    <div class="row">
                        <fieldset>
                            <legend>Thông tin đơn thuốc</legend>
                            <?php
                            $form = new FormDonThuoc();
                            $donthuoc = new DonThuoc();
                            ?>
                            <div class="col-md-9">
                                <?php echo $form->TongNgayDung($_SESSION["SoNgaySDThuoc"] ?? 0)->renderHTML(); ?>
                            </div>
                            </br>
                            <div class="form-group" style="margin-top: 5px;">
                                <?php btnHtml::btnCapNhatNgayDung(); ?>
                            </div>

                            <div class="col-md-12">
                                <?php echo $form->ThuocLoaiDon()->renderHTML(); ?>
                            </div>
                            <div class="col-md-12">
                                <?php echo $form->ChanDoanBenh()->renderHTML(); ?>
                            </div>
                            <div class="col-md-12">
                                <?php echo $form->Id($donthuoc->CreatId())->renderHTML(); ?>
                            </div>
                            <div class="col-md-12">
                                <?php echo $form->ThoiGianKham(date('Y-m-d H:i:s', time()))->renderHTML(); ?>
                            </div>
                        </fieldset>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="row">
                        <fieldset>
                            <legend>Thông tin bệnh nhân</legend>
                            <div class="col-md-6">
                                <?php $bn->Name(null, 'tenbenhnhan')->renderHtml();  ?>
                            </div>
                            <div class="col-md-6">
                                <?php $bn->Phone(null, 'sodienthoai')->renderHtml();  ?>
                            </div>
                            <div class="col-md-6">
                                <?php $bn->CMND()->renderHtml();  ?>
                            </div>
                            <div class="col-md-6">
                                <?php $bn->Gioitinh()->renderHtml();  ?>
                            </div>
                            <div class="col-md-4">
                                <?php $bn->Namsinh()->renderHtml();  ?>
                            </div>
                            <div class="col-md-4">
                                <?php $bn->Thangsinh()->renderHtml();  ?>
                            </div>

                            <div class="col-md-4">
                                <?php $bn->Ngaysinh()->renderHtml();  ?>
                            </div>
                            <div class="col-md-12">
                                <?php $bn->Address()->renderHtml();  ?>
                            </div>
                            <div class="col-md-4 form-group">
                                <label for="">Tỉnh</label>
                                <select id="tinhThanh" name="BenhNhan[TinhThanh]" class="form-control"></select>
                            </div>
                            <div class="col-md-4 form-group">
                                <label for="">Huyện</label>
                                <select id="quanHuyen" name="BenhNhan[QuanHuyen]" class="form-control"> </select>

                            </div>
                            <div class="col-md-4 form-group">
                                <label for="">Xã</label>
                                <select id="phuongXa" name="BenhNhan[PhuongXa]" class="form-control phuong-xa"> </select>
                            </div>
                        </fieldset>
                    </div>
                </div>
                <fieldset>
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>
                                    <button data-toggle="tooltip" data-placement="top" title="Thêm thuốc mới" type="button" class="btn btn-success" id="btn-add">
                                        <i class="fa fa-plus" aria-hidden="true"></i>
                                    </button>
                                </th>
                                <th>STT</th>
                                <th>Tên Thuốc</th>
                                <th>SL tồn</th>
                                <th>Số Ngày Dùng</th>
                                <th>Cách Dùng</th>
                                <th>Đơn Vị Tính</th>
                                <th>Sáng</th>
                                <th>Trưa</th>
                                <th>Chiều</th>
                                <th>Số Lượng</th>
                                <th>Ghi Chú</th>
                            </tr>
                        </thead>
                        <tbody class="table-thuoc">
                            <?php
                            // var_dump(DonThuocDetail::DsThuoc());
                            $i = 0;
                            foreach (DonThuocDetail::DsThuoc() as $mathuoc => $thuoc) {
                                $sanPham = new SanPham($thuoc["Id"] ?? null);
                                $i = $mathuoc;
                            ?>
                                <tr>
                                    <th>
                                        <button data-toggle="tooltip" data-placement="top" title="Xóa thuốc" type="button" title="Xóa thuốc này?" class="btn  btn-danger deleterows" id="<?php echo 'delete' . $i ?>" index=<?php echo $i ?>>
                                            <i class="fa fa-minus" aria-hidden="true"></i>
                                        </button>
                                    </th>
                                    <td style="display: table-cell; vertical-align: middle;">
                                        <div class="text-center">
                                            <?php echo $i + 1; ?>
                                        </div>
                                    </td>
                                    <th style="width: 200px;">
                                        <?php
                                        echo $form->Name($thuoc["Id"] ?? "", "donthuoc" . $i, $i)->renderHTML();
                                        ?>
                                    </th>
                                    <td style="width: 80px;">
                                        <?php echo $form->SLHienTai($sanPham->SLHienTai ?? "", "SLHienTai" . $i, $i)->render(); ?>
                                    </td>
                                    <td style="width: 150px;">
                                        <?php echo $form->SoNgaySDThuoc($thuoc["SoNgaySDThuoc"] ?? "", "SoNgaySD" . $i, $i)->render(); ?>
                                    </td>
                                    <td style="width: 100px;">
                                        <?php echo $form->CachDung($sanPham->CachDungThuoc(), "cachdungthuoc" . $i, $i)->render(); ?>
                                    </td>
                                    <td style="width: 100px;">
                                        <?php echo $form->DVT($sanPham->DonViTinh(), "dvt" . $i, $i)->render(); ?>
                                    </td>
                                    <td style="width: 80px;">
                                        <?php echo $form->Sang($thuoc["Sang"] ?? "", "sang" . $i, $i)->render(); ?>
                                    </td>
                                    <td style="width: 80px;">
                                        <?php echo $form->Trua($thuoc["Trua"] ?? "", "trua" . $i, $i)->render(); ?>
                                    </td>
                                    <td style="width: 80px;">
                                        <?php echo $form->Chieu($thuoc["Chieu"] ?? "", "chieu" . $i, $i)->render(); ?>
                                    </td>
                                    <td style="width: 80px;">
                                        <?php echo $form->SoLuong($thuoc["Soluong"] ?? "", "soluong" . $i, $i)->render(); ?>
                                    </td>
                                    <td>
                                        <?php echo $form->GhiChu($sanPham->Ghichu, "ghichu" . $i, $i)->render(); ?>
                                    </td>
                                </tr>
                            <?php
                                $i++;
                            }
                            ?>
                        </tbody>
                    </table>
                </fieldset>
                <div class="col-md-12 ">
                    <button class="btn btn-warning" type="reset">Làm lại</button>
                    <button class="btn btn-success" name="LuuThoat">Thêm đơn thuốc mới</button>
                </div>
            </form>
        </div>
    </div>
</div>


<script src="/Module/donthuoc/public/postdonthuoc.js"></script>
<script src="/public/TinhThanh/tinhthanh.js"></script>