<ol class="breadcrumb">
    <li><a href="/index.php?controller=backend">Home</a></li>
    <li><a href="/index.php?module=donthuoc&controller=index&action=index"> Danh Sách Toa Thuốc</a></li>
    <li> Thêm Toa Thuốc </li>
</ol>
<?php

use Model\FormRender;
use Module\benhnhan\Model\BenhNhan;
use Module\benhnhan\Model\BenhNhan\FormBenhNhan;
use Module\donthuoc\Model\btnHtml;
use Module\donthuoc\Model\DonThuoc\FormDonThuoc;
use Module\donthuoc\Model\DonThuocDetail;
use Module\quanlythuoc\Model\SanPham;

$roleDetail = new Model\Role();
?>
<div class="container-fluid">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Thêm Toa Thuốc</h3>
            <div class="box-tools">
                <?php
                FormRender::HuongDan("huongdandonthuoc");
                ?>
            </div>
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            <div class="box-body">
                <?php
                $bn = new FormBenhNhan();
                $benhnhan = new BenhNhan();
                ?>
                <div class="">
                    <div class="col-md-4">
                        <?php $bn->Id($benhnhan->CreatId())->renderHTML(); ?>
                    </div>
                    <div class="col-md-4">
                        <?php $bn->Name()->renderHTML();  ?>
                    </div>
                    <div class="col-md-4">
                        <?php $bn->Gioitinh()->renderHtml();  ?>
                    </div>
                    <div class="col-md-4">
                        <?php $bn->Ngaysinh()->renderHtml();  ?>
                    </div>
                    <div class="col-md-4">
                        <?php $bn->CMND()->renderHtml();  ?>
                    </div>
                    <div class="col-md-4">
                        <?php $bn->Phone()->renderHtml();  ?>
                    </div>
                    <div class="col-md-12">
                        <?php $bn->Address()->renderHtml();  ?>
                    </div>
                    <div class="col-md-4 form-group">
                        <label for="">Tỉnh</label>
                        <select id="tinhThanh" name="BenhNhan[TinhThanh]" class="form-control"></select>
                    </div>
                    <div class="col-md-4 form-group">
                        <label for="">Huyện</label>
                        <select id="quanHuyen" name="BenhNhan[QuanHuyen]" class="form-control"> </select>

                    </div>
                    <div class="col-md-4 form-group">
                        <label for="">Xã</label>
                        <select id="phuongXa" name="BenhNhan[PhuongXa]" class="form-control"> </select>
                    </div>
                    <div class="col-md-12 ">
                        <button class="btn btn-warning" type="reset">Làm Lại</button>
                        <!-- <button class="btn btn-success">Lưu</button> -->
                        <button class="btn btn-success" name="LuuThoat">Thêm Mới</button>
                    </div>
                </div>

                <?php
                $form = new FormDonThuoc();
                ?>
                <div class="col-md-4">
                    <?php echo $form->TongNgayDung($_SESSION["SoNgaySDThuoc"] ?? 0)->renderHTML(); ?>
                </div>
                <div class="col-md-6">
                    </br>
                    <div class="form-group" style="margin-top: 5px;">
                        <?php btnHtml::btnCapNhatNgayDung(); ?>
                    </div>
                </div>

                <div class="col-md-3">
                    <?php echo $form->ThoiGianKham()->renderHTML(); ?>
                </div>
                <div class="col-md-3">
                    <?php echo $form->ThuocLoaiDon()->renderHTML(); ?>
                </div>
                <div class="col-md-3">
                    <?php echo $form->IdBenhNhan()->renderHTML(); ?>
                </div>
                <div class="col-md-3">
                    <?php echo $form->ChanDoanBenh()->renderHTML(); ?>
                </div>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>STT</th>
                            <th>Tên Thuốc</th>
                            <th>Số lượng còn</th>
                            <th>Số Ngày Dùng</th>
                            <th>Cách Dùng</th>
                            <th>Đơn Vị Tính</th>
                            <th>Sáng</th>
                            <th>Trưa</th>
                            <th>Chiều</th>
                            <th>Số Lượng</th>
                            <!-- <th>Giá Bán</th> -->
                            <th>Ghi Chú</th>
                        </tr>
                    </thead>
                    <tbody class="table-thuoc">
                        <?php
                        // var_dump(DonThuocDetail::DsThuoc());
                        $i = 0;
                        foreach (DonThuocDetail::DsThuoc() as $mathuoc => $thuoc) {
                            $sanPham = new SanPham($thuoc["Id"] ?? null);

                        ?>
                            <tr>
                                <th style="display: table-cell; vertical-align: middle;">
                                    <div class="text-center">
                                        <?php echo $i + 1; ?>
                                    </div>
                                </th>
                                <th style="width: 250px;">
                                    <?php
                                    echo $form->Name($thuoc["Id"] ?? "", "donthuoc" . $i, $i)->renderHTML();
                                    ?>
                                </th>
                                <th>
                                    <?php echo $form->SLHienTai($sanPham->SLHienTai ?? "", "SLHienTai" . $i, $i)->render(); ?>
                                </th>
                                <th style="width:120px;">
                                    <?php echo $form->SoNgaySDThuoc($thuoc["SoNgaySDThuoc"] ?? "", "SoNgaySD" . $i, $i)->render(); ?>
                                </th>
                                <th style="width: 150px;">
                                    <?php echo $form->CachDung($sanPham->CachDung, "cachdungthuoc" . $i, $i)->render(); ?>
                                </th>
                                <th style="width: 100px;">
                                    <?php echo $form->DVT($sanPham->DonViTinh(), "dvt" . $i, $i)->render(); ?>
                                </th>
                                <th style="width: 100px;">
                                    <?php echo $form->Sang($thuoc["Sang"] ?? "", "sang" . $i, $i)->render(); ?>
                                </th>
                                <th style="width: 100px;">
                                    <?php echo $form->Trua($thuoc["Trua"] ?? "", "trua" . $i, $i)->render(); ?>
                                </th>
                                <th style="width: 100px;">
                                    <?php echo $form->Chieu($thuoc["Chieu"] ?? "", "chieu" . $i, $i)->render(); ?>
                                </th>
                                <th>
                                    <?php echo $form->SoLuong($thuoc["Soluong"] ?? "", "soluong" . $i, $i)->render(); ?>
                                </th>
                                <!-- <th>
                                    <?php echo $form->GiaBan($sanPham->Giaban ?? null, "giaban" . $i, $i)->render(); ?>
                                </th> -->
                                <th>
                                    <?php echo $form->GhiChu($sanPham->Ghichu, "ghichu" . $i, $i)->render(); ?>
                                </th>
                            </tr>

                        <?php
                            $i++;
                        }
                        ?>
                    </tbody>
                </table>

                <div class="col-md-12 ">
                    <button class="btn btn-warning" type="reset">Làm Lại</button>
                    <!-- <button class="btn btn-success">Lưu</button> -->
                    <button class="btn btn-success" name="LuuThoat">Thêm Toa Thuốc Mới</button>
                </div>
            </div>
        </form>
    </div>
</div>
<script>
    $(document).ready(function() {

        // Xử lý dữ liệu sáng, trưa, chiều, số lượng thuốc
        $(".changenumber").each(function(index, e) {
            // console.log(e.attr("id"));
            $(this).change(function(param) {
                // console.log($(this).attr("id"));
                $($(this).attr("id")).val();
                // console.log($("#"+$(this).attr("id")).val());
                console.log($("#" + $(this).attr("id")).attr("index"));
                var idName = "#" + $(this).attr("id");
                var idDVT = "#dvt" + $("#" + $(this).attr("id")).attr("index");
                var index = $("#" + $(this).attr("id")).attr("index");
                var idThuoc = $(idName).val();
                var idSoNgaySD = "#SoNgaySD" + $("#" + $(this).attr("id")).attr("index");
                var idSang = "#sang" + $("#" + $(this).attr("id")).attr("index");
                var idTrua = "#trua" + $("#" + $(this).attr("id")).attr("index");
                var idChieu = "#chieu" + $("#" + $(this).attr("id")).attr("index");
                var idSoLuong = "#soluong" + $("#" + $(this).attr("id")).attr("index");
                var idGiaBan = "#giaban" + $("#" + $(this).attr("id")).attr("index");

                $.ajax({
                    url: `/donthuoc/index/capnhatsoluong/`,
                    type: 'post',
                    dataType: 'json',
                    contentType: 'application/json; charset=utf-8',
                    // data: JSON.stringify(data),
                    data: JSON.stringify({
                        "index": index,
                        "sang": $(idSang).val(),
                        "chieu": $(idChieu).val(),
                        "trua": $(idTrua).val(),
                        "ngaydungthuoc": $(idSoNgaySD).val(),
                    }),
                    contentType: false,
                    processData: false,
                    success: function(response) {
                        console.log(response);
                        $(idGiaBan).val(response.Giaban);
                        $(idDVT).val(response.DVTTitle);
                        $(idSang).val(response.Sang);
                        $(idTrua).val(response.Trua);
                        $(idChieu).val(response.Chieu);
                        $(idSoNgaySD).val(response.SoNgaySDThuoc);
                        $(idSoLuong).val(response.Soluong);
                    },
                    complete: function() {
                        //spinner.close();
                    }
                });
            });
        });

        // Xử lý nút button Cập nhật tổng ngày dùng
        $("#btn-capnhattongngaydungthuoc").click(function() {
            var TongNgayDungThuoc = $("#TongNgayDungThuoc").val();
            $.ajax({
                url: `/donthuoc/index/capnhatngaydungthuoc/${TongNgayDungThuoc}/`,
                type: 'Get',
                // data:{$id : $id},
                //dataType: 'json',
                contentType: false,
                processData: false,
                success: function(response) {
                    console.log(response);
                    window.location.reload();
                },
                complete: function() {
                    //spinner.close();
                }
            });
        })

        // Thay đổi dữ liệu khi change name thuốc
        $(".changename").each(function(index, e) {
            // console.log(e.attr("id"));
            $(this).change(function(param) {
                // console.log($(this).attr("id"));
                $($(this).attr("id")).val();
                // console.log($("#"+$(this).attr("id")).val());
                // console.log($("#" + $(this).attr("id")).attr("index"));
                var index = $("#" + $(this).attr("id")).attr("index");
                var idName = "#" + $(this).attr("id");
                var idDVT = "#dvt" + index;
                var idThuoc = $(idName).val();
                var idSoNgaySD = "#SoNgaySD" + index;
                var idSang = "#sang" + index;
                var idTrua = "#trua" + index;
                var idChieu = "#chieu" + index;
                var idSoLuong = "#soluong" + index;
                var idSLHienTai = "#SLHienTai" + index;
                var idGiaBan = "#giaban" + index;
                var idCachDungThuoc = "#cachdungthuoc" + index;
                var idGhiChu = "#ghichu" + index;

                console.log(idDVT);
                console.log(index);
                console.log(idThuoc);
                console.log(idCachDungThuoc);

                $.ajax({
                    url: `/donthuoc/index/capnhatthuoc/${idThuoc}/${index}/`,
                    type: 'Get',
                    // data:{$id : $id},
                    //dataType: 'json',
                    contentType: false,
                    processData: false,
                    success: function(response) {
                        console.log(response);
                        // console.log("ádasdsadsdadasdsd");
                        if (response.SoNgaySDThuoc == null) {
                            alert("Thuốc đã có trong danh sách");
                            console.log(idName);
                            window.location.reload();
                            $(idName).val("");
                            console.log($(idName + " option:selected").val());
                            return;
                        }
                        console.log(response);
                        $(idGiaBan).val(response.Giaban);
                        $(idDVT).val(response.DVTTitle);
                        $(idSang).val(response.Sang);
                        $(idTrua).val(response.Trua);
                        $(idChieu).val(response.Chieu);
                        $(idSoNgaySD).val(response.SoNgaySDThuoc);
                        $(idSoLuong).val(response.Soluong);
                        $(idCachDungThuoc).val(response.CachDung);
                        $(idGhiChu).val(response.Ghichu);
                        $(idSLHienTai).val(response.SLHienTai);
                    },
                    complete: function() {
                        //spinner.close();
                    }
                });
            });
        });
    });
</script>