<?php

use Module\cart\Model\Order;
use PhpOffice\PhpSpreadsheet\Calculation\DateTimeExcel\Days;
use Common\Common;
use Model\Products;
use Module\donthuoc\Model\DonThuoc;
use Module\quanlythuoc\Model\SanPham;

?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<style>
    @media print {

        .no-print,
        .no-print * {
            display: none !important;
        }
    }

    .main {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        border: 1px solid #000;
    }

    .salesslip {
        width: 500px;
        margin: auto;
    }

    .shop {
        text-align: center;
    }

    /* ------------------------------ */
    .temporary {
        margin: 0 25px;
        display: flex;
        justify-content: space-around;
        margin-bottom: 15px;
    }

    td.temporary-title {
        padding-right: 7px;
    }

    /* ------------------------------ */
    .content {
        display: flex;
        justify-content: center;
        align-items: flex-start;
        min-height: unset;
    }

    /* ------------------------------ */
    .total-order {
        display: flex;
        flex-basis: 50%;
        justify-content: space-between;
        margin-top: 10px;
    }

    .total-order p {
        font-size: 17px;
        margin: 5px 0;
    }

    /* ------------------------------ */
    .footer {
        text-align: center;
    }

    .btn {
        margin-left: 50%;
        padding: 5px 30px;
        transform: translateX(-50%);
        border-radius: 10px;
        border: 1px solid #9e9e9e;
        margin-bottom: 10px;
    }

    .btn:hover {
        color: #000;
        cursor: pointer;
        background-color: #6b6565ba;
    }
</style>
<?php
$donthuoc  = new DonThuoc($donthuoc);
$IdDonThuoc = $donthuoc->Id;
// var_dump($donthuoc);
?>

<body>
    <div class="main">
        <div class="salesslip">
            <div class="shop">
                <h2>PHÒNG KHÁM PHƯƠNG UYÊN</h2>
                <h5>ĐC: 176 đường số 18,Bình Hưng Hòa,Bình Tân</h5>
                <h5>Giờ làm việc: Sáng 7h30 - 11h, Chiều 17h - 20h30 (Nghỉ thứ 7)</h5>
                <h3 style="margin: 0px;">ĐƠN THUỐC</h3>
                <h5 style=" font-weight: 500; margin: 10px 0;">
                    <?php $date = getdate();
                    // echo $date['weekday'] . ", ";
                    echo "Ngày " . $date['mday'] . " ";
                    echo "/ " . $date['mon'] . " ";
                    echo "/ " . $date['year'] . " - ";
                    echo $date['hours'] . " " . "giờ" . " ";
                    echo $date['minutes'] . " " . " phút" . " ";
                    echo $date['seconds'] . " " . " giây" . " ";
                    ?>
                </h5>
                <!-- <h5 style="font-style: italic ;font-weight: 300; margin: 10px 0;">
                    <?php $date = getdate();
                    echo $date['hours'] . " " . "giờ" . " ";
                    echo $date['minutes'] . " " . " phút" . " ";
                    echo $date['seconds'] . " " . " giây" . " ";
                    ?>
                </h5> -->
                <h5 style="font-style: italic ;font-weight: 400; margin: 10px 0;">
                    Mã đơn: <?php echo $donthuoc->Id; ?>
                </h5>
            </div>
            <!---------------------------------->
            <div style="margin: 0; border-bottom: 1px solid #00000042">
                <table class="table table-hover">
                    <thead>
                        <th>
                        <td>Họ và tên : <?php echo $donthuoc->NameBN; ?></td>
                        </th>
                        <th>
                        <td>Tuổi : <?php echo date('Y') - date('Y', strtotime($donthuoc->NgaySinh)); ?></td>
                        </th>
                    </thead>
                    <thead>
                        <th>
                        <td>Chẩn đoán : <?php echo $donthuoc->ChanDoanBenh; ?></td>
                        </th>
                        <th>
                        <td>Phái : <?php echo $donthuoc->GioiTinh(); ?></td>
                        </th>
                    </thead>
                </table>
            </div>

            <div style="margin: 0; border-bottom: 1px solid #00000042">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>STT</th>
                            <th>Tên thuốc</th>
                            <th>Số lượng</th>
                            <th></th>
                            <th>Ghi chú</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $detail = DonThuoc::GetDetailById($IdDonThuoc);
                        // var_dump($detail);
                        foreach ($detail as $index => $DTdetail) { ?>
                            <tr>
                                <td><?php echo $index + 1 ?></td>
                                <th><?php echo SanPham::GetNameById($DTdetail['IdThuoc']); ?></th>
                                <td><?php echo $DTdetail['SoLuong'] . ' ' . $DTdetail['DVT']; ?></td>
                                <td></td>
                                <td><?php echo $DTdetail['GhiChu']; ?></td>
                            </tr>
                            <tr>
                                <td></td>
                                <td>Sáng: <?php echo SanPham::GetDesByVal($DTdetail['Sang'],'donviquydoi') . ' ' . $DTdetail['DVT']; ?></td>
                                <td>Trưa: <?php echo SanPham::GetDesByVal($DTdetail['Trua'],'donviquydoi') . ' ' . $DTdetail['DVT']; ?></td>
                                <td>Chiều: <?php echo SanPham::GetDesByVal($DTdetail['Chieu'],'donviquydoi') . ' ' . $DTdetail['DVT']; ?></td>
                            </tr>
                        <?php
                        }
                        ?>

                    </tbody>
                </table>

            </div>



            <!---------------------------------->
            <div class="row text-center">
                <div class="col-md-6"></div>
                <div class="col-md-6">
                    <h5 style=" font-weight: 500; margin: 10px 0;">
                        <?php $date = getdate();
                        // echo $date['weekday'] . ", ";
                        echo "Ngày " . $date['mday'] . " ";
                        echo "Tháng " . $date['mon'] . " ";
                        echo "Năm " . $date['year'] . "";
                        ?>
                    </h5>
                    <h5>Bác Sỹ</h5><br><br>
                </div>
            </div>
            <div class="footer">
                <h5 style="margin: 10px 0; letter-spacing: 0.7 px; font-style: italic;">
                    Khi tái khám nhớ mang theo đơn thuốc
                </h5>
            </div>
            <button type="submit" onclick="window.print()" class="no-print btn">
                Print
            </button>
        </div>
    </div>
</body>