<?php

use Module\cart\Model\Order;
use PhpOffice\PhpSpreadsheet\Calculation\DateTimeExcel\Days;
use Model\Products;
use Module\donthuoc\Model\DonThuoc;
use Module\quanlythuoc\Model\SanPham;
use Module\benhnhan\Model\BenhNhan;
use Model\Common;
use PhpOffice\PhpSpreadsheet\Calculation\MathTrig\Sum;

?>
<style>
    @media print {

        .no-print,
        .no-print * {
            display: none !important;
        }
    }

    .main {
        margin: 0;
        padding: 0;
    }

    .salesslip {
        width: 500px;
        margin: auto;
    }

    .shop {
        text-align: center;
    }

    /* ------------------------------ */
    .temporary {
        margin: 0 25px;
        display: flex;
        justify-content: space-around;
        margin-bottom: 15px;
    }

    td.temporary-title {
        padding-right: 7px;
    }

    /* ------------------------------ */
    .content {
        display: flex;
        justify-content: center;
        align-items: flex-start;
        min-height: unset;
    }

    /* ------------------------------ */
    .total-order {
        display: flex;
        flex-basis: 50%;
        justify-content: space-between;
        margin-top: 10px;
    }

    .total-order p {
        font-size: 17px;
        margin: 5px 0;
    }

    /* ------------------------------ */
    .footer {
        text-align: center;
    }

    .btn {
        margin-left: 50%;
        padding: 5px 30px;
        transform: translateX(-50%);
        border-radius: 10px;
        border: 1px solid #9e9e9e;
        margin-bottom: 10px;
    }

    .btn:hover {
        color: #000;
        cursor: pointer;
        background-color: #6b6565ba;
    }
</style>
<?php
$donthuoc  = new DonThuoc($donthuoc);
$IdDonThuoc = $donthuoc->Id;
// var_dump($donthuoc);
?>
<div class="box box-default" style="border: none;">
    <div class="main main-body">
        <div class="salesslip">
            <div class="shop">
                <h4 style="margin: 0px; margin-top:5px;"><b>PHÒNG KHÁM PHƯƠNG UYÊN</b></h4>
                <span style="font-size: 11px;">ĐC: 176 đường số 18,Bình Hưng Hòa,Bình Tân. Giờ làm việc: Sáng 7h30 - 11h, Chiều 17h - 20h30 (Nghỉ thứ 7)</span>
                <span><b>ĐƠN THUỐC</b></span>
                <!-- <h5 style=" font-weight: 500; margin: 10px 0;">
                    <?php $date = getdate();
                    // echo $date['weekday'] . ", ";
                    echo "Ngày " . $date['mday'] . " ";
                    echo "/ " . $date['mon'] . " ";
                    echo "/ " . $date['year'] . " - ";
                    echo $date['hours'] . " " . "giờ" . " ";
                    echo $date['minutes'] . " " . " phút" . " ";
                    echo $date['seconds'] . " " . " giây" . " ";
                    ?>
                </h5> -->
                <!-- <h5 style="font-style: italic ;font-weight: 300; margin: 10px 0;">
                    <?php $date = getdate();
                    echo $date['hours'] . " " . "giờ" . " ";
                    echo $date['minutes'] . " " . " phút" . " ";
                    echo $date['seconds'] . " " . " giây" . " ";
                    ?>
                </h5> -->
                <!-- <h5 style="font-style: italic ;font-weight: 400; margin: 10px 0;">
                    Mã đơn: <?php echo $donthuoc->Id; ?>
                </h5> -->
            </div>
            <!---------------------------------->
            <div style="margin: 0; border-bottom: 1px solid #00000042">
                <table class="table-hover" style="width: 100%;">
                    <thead>
                        <th>
                        <td>Họ và tên : <?php echo $donthuoc->NameBN; ?></td>
                        </th>
                        <th>
                        <td>Tuổi : <?php echo date('Y') - date('Y', strtotime($donthuoc->NgaySinh)); ?></td>
                        </th>
                    </thead>
                    <thead>
                        <th>
                        <td>Quê quán : <?php echo DonThuoc::GetItemById('Address', $donthuoc->IdBenhNhan); ?></td>
                        </th>
                        <th>
                        <td>Giới tính : <?php echo $donthuoc->GioiTinh(); ?></td>
                        </th>
                    </thead>
                    <thead>
                        <th>
                        <td>Số điện thoại : <?php echo DonThuoc::GetItemById('Phone', $donthuoc->IdBenhNhan); ?></td>
                        </th>
                        <th>
                        <td>Chẩn đoán : <?php echo $donthuoc->ChanDoanBenh; ?></td>
                        </th>
                    </thead>
                </table>
            </div>

            <div style="margin: 0; border-bottom: 1px solid #00000042">
                <table style="width: 100%;">
                    <thead>
                        <tr>
                            <th>STT</th>
                            <th class="text-center">Tên thuốc</th>
                            <th>Số lượng</th>
                            <th>Đơn giá</th>
                            <th>Thành Tiền</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $detail = DonThuoc::GetDetailById($IdDonThuoc);
                        $common = new Common();
                        // var_dump($detail);
                        $sum = 0;
                        foreach ($detail as $index => $DTdetail) { ?>
                            <tr>
                                <td class="text-center"><b><?php echo $index + 1 ?></b></td>
                                <th><?php echo SanPham::GetNameById($DTdetail['IdThuoc']); ?></th>
                                <td><span style="font-weight: 400 !important;"><?php echo $DTdetail['SoLuong'] . ' ' . $DTdetail['DVT']; ?></span></td>
                                <td><?php echo Common::ViewNumber($DTdetail['GiaBan']); ?></td>
                                <td><?php echo Common::ViewPrice($DTdetail['SoLuong'] * $DTdetail['GiaBan']); ?></td>
                                <td><?php $sum += $DTdetail['SoLuong'] * $DTdetail['GiaBan'] ?></td>
                            </tr>
                            <tr >
                                <td></td>
                                <td>Sáng: <b><?php echo SanPham::GetDesByVal($DTdetail['Sang'], 'donviquydoi') . ' ' . $DTdetail['DVT']; ?></b></td>
                                <td>Trưa: <b><?php echo SanPham::GetDesByVal($DTdetail['Trua'], 'donviquydoi') . ' ' . $DTdetail['DVT']; ?></b></td>
                                <td>Chiều: <b><?php echo SanPham::GetDesByVal($DTdetail['Chieu'], 'donviquydoi') . ' ' . $DTdetail['DVT']; ?></b></td>
                            </tr>
                        <?php
                        }
                        ?>
                    </tbody>
                </table>
            </div>
            <tr>
                <td><b>Tổng cộng :</b> <?php echo Common::ViewPrice($sum)." "."( ".$common->convert_number_to_words($sum)." )"?></td>
            </tr>
            <!---------------------------------->
            <div class="row">
                <div class="col-xs-6"></div>
                <div class="col-xs-6 text-center">
                    <h6 style=" font-weight: 500; margin: 10px 0;">
                        <i><?php $date = getdate();
                            // echo $date['weekday'] . ", ";
                            echo "Ngày " . $date['mday'] . " ";
                            echo "Tháng " . $date['mon'] . " ";
                            echo "Năm " . $date['year'] . "";
                            ?></i>
                    </h6>
                    <h6>Bác Sỹ</h6><br><br>
                </div>
            </div>
            <div class="footer">
                <h5 style="margin: 10px 0; letter-spacing: 0.7 px; font-style: italic;text-align: left;">
                    <b>* Khi tái khám nhớ mang theo đơn thuốc</b>
                </h5>
            </div>
            <button type="submit" onclick="window.print()" class="no-print btn">
                Print
            </button>
        </div>
    </div>
</div>