<ol class="breadcrumb">
    <li><a href="/backend">Home</a></li>
    <li> Phiếu Hẹn</li>
</ol>
<div class="container-fluid" ng-controller="searchCtrl">
    <form method="get" action="/nhanvien/index/index/">
        <div class="form-group d-flex">
            <label class="btn btn-default"><input ng-change="isShowMore(showMore);" ng-model="showMore"
                    style="display: none" type="checkbox"><i class="fa fa-filter"></i></label>
            <input id="keyword" class="form-control" name="keyword"
                value="<?php echo isset($_GET["keyword"]) ? \Model\Common::TextInput($_GET["keyword"]) : "" ?>" type="">
            <button class="btn btn-primary no-border-radius" name="btnTim" type="submit">
                <i class="fa fa-search"></i>
            </button>
        </div>
        <div class="row " ng-show="showMore">
            <div class="col-md-3">
                <?php
                $options = \Model\OptionsService::GetGroupsToSelect("congty");
                $options = ["" => "Chọn Công Ty"] + $options;
                $congty = isset($_GET[Model\Users\UserInfor::CongTy]) ? $_GET[Model\Users\UserInfor::CongTy] : "";
                Model\FormCommon::Select("Công Ty", Model\Users\UserInfor::CongTy, $options, ["value" => $congty, "class" => "form-control"])->renderHTML();
                ?>
            </div>
        </div>
    </form>
    <div class="clearfix">

    </div>
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Danh Sách Phiếu Hẹn</h3>
        </div>
        <div class="box-body">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th style="width: 100px" class="hidden-xs"> </th>
                        <th>Họ Tên</th>
                        <th>SDT</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($Items as $index => $user) {
                        $_user = new \Module\nhanvien\Model\NhanVien($user);
                        ?>
                        <tr>
                            <th class="text-center hidden-xs">

                            </th>

                        </tr>
                        <?php
                    }
                    ?>
                </tbody>
            </table>

        </div>
        <div class="box-footer">
            <div class="d-flex">
                <?php
                \Model\FormCommon::Select(
                    "",
                    "",
                    [10, 20, 50, 100],
                    [
                        "style" => "max-width:70px;",
                        "class" => "form-control",
                        "value" => $pageNumber,
                        "onchange" => "SoDongHienThi(this.value)",
                    ]
                )->render();
                ?>
                <?php
                $linkPhanTrang = "/nhanvien/index/index/?indexPage=[i]&pageNumber={$pageNumber}";
                echo \Model\Common::PhanTrang($total, $indexPage, $pageNumber, $linkPhanTrang);
                ?>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var SoDongHienThi = function (evalue) {
        var linkPhanTrang = '/nhanvien/index/index/?indexPage=1&pageNumber=[j]';
        linkPhanTrang = linkPhanTrang.replace("[j]", evalue);
        window.location.href = linkPhanTrang;
    }
</script>