<ol class="breadcrumb">
    <li><a href="/datlich/index/post">Đặt Lịch</a></li>
    <li> Đặt Lịch Khám</li>
</ol>
<div class="container">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Đặt lịch khám</h3>
        </div>
        <div class="box-body">
            <form action="" method="post">
                <?php
                use Module\datlich\Model\DatLichForm;

                $dlForm = new DatLichForm();
                ?>
                <div class="row">
                    <div class="col-md-4">
                        <?php
                        echo $dlForm->FULLNAME()->renderHTML();
                        ?>
                    </div>
                    <div class="col-md-4">
                        <?php
                        echo $dlForm->PHONE()->renderHTML();
                        ?>
                    </div>
                    <div class="col-md-4">
                        <?php
                        echo $dlForm->EMAIL()->renderHTML();
                        ?>
                    </div>
                    <div class="col-md-12">
                        <?php
                        echo $dlForm->ADDRESS()->renderHTML();
                        ?>
                    </div>
                    <div class="col-md-6">
                        <?php
                        echo $dlForm->SERVICENAME()->renderHTML();
                        ?>
                    </div>
                    <div class="col-md-6">
                        <?php
                        echo $dlForm->DATEEXAMINATION()->renderHTML();
                        ?>
                    </div>
                </div>
                <div class="text-right">
                    <button class="btn btn-success">Gửi</button>
                </div>

            </form>

        </div>
    </div>
</div>
<script type="text/javascript">
    var SoDongHienThi = function (evalue) {
        var linkPhanTrang = '/nhanvien/index/index/?indexPage=1&pageNumber=[j]';
        linkPhanTrang = linkPhanTrang.replace("[j]", evalue);
        window.location.href = linkPhanTrang;
    }
</script>