<ol class="breadcrumb">
    <li><a href="/index.php?controller=backend">Home</a></li>
    <li> Quản Lý Khách Hàng </li>
</ol>

<div class="container-fluid">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Danh Sách Khách Hàng</h3>
            <div class="box-tools">
                <?php

use Model\Locations;
use Model\OptionsService;
use Module\benhnhan\Model\BenhNhan;

                Module\benhnhan\Model\btnHtml::btnThemKhachHang();
                ?>
            </div>
        </div>
        <div class="box-body">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th></th>
                        <th>STT</th>
                        <th>Mã Bệnh Nhân</th>
                        <th>Tên Bệnh Nhân</th>
                        <th>Giới Tính</th>
                        <th>Ngày Sinh</th>
                        <th>CMND</th>
                        <th>Địa Chỉ</th>
                        <th>Quê Quán</th>
                        <th>Điện Thoại</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($items as $index => $item) {
                        $_item = new BenhNhan($item);

                        // // Lấy huyện theo mã Id
                        // $location = new Locations();
                        // $a = $location->GetByIdParents(78);
                        // $b = $a[0];
                        // foreach ($a as $item) {
                        //     // var_dump($item[1]);
                        // }

                        // // --------------------------------

                        // $c = $location->GetIdParent();

                        // $d = json_encode($c);
                        // echo $d;
                        // var_dump($b);
                        // echo $b["Name"];
                    ?>
                        <tr>
                            <th style="width: 150px;">
                                <?php
                                echo Module\benhnhan\Model\btnHtml::btnSuaKhachHang($_item->Id);
                                echo Module\benhnhan\Model\btnHtml::btnXoaKhachHang($_item->Id);
                                ?>
                            </th>
                            <th><?php echo $index + 1; ?></th>
                            <th><?php echo $_item->Id; ?></th>
                            <th><?php echo $_item->Name; ?></th>
                            <th><?php echo $_item->Gioitinh; ?></th>
                            <th><?php echo $_item->Ngaysinh; ?></th>
                            <th><?php echo $_item->CMND; ?></th>
                            <th><?php echo $_item->Address; ?></th>
                            <th><?php echo $_item->Quequan; ?></th>
                            <th><?php echo $_item->Phone; ?></th>
                        </tr>
                    <?php
                    }
                    ?>
                </tbody>
            </table>
            <div class="box-footer">
                <div class="d-flex">
                    <?php
                    \Model\FormCommon::Select(
                        "",
                        "",
                        [10, 20, 50, 100],
                        [
                            "style" => "max-width:150px;",
                            "class" => "form-control",
                            "value" => $pageNumber,
                            "onchange" => "SoDongHienThi(this.value)",
                        ]
                    )->render();
                    ?>
                    <?php
                    $linkPhanTrang = "/index.php?module=quanlythuoc&controller=danhmuc&action=index&keyword={$params["keyword"]}&indexPage=[i]&pageNumber={$pageNumber}";
                    echo \Model\Common::PhanTrang($total, $indexPage, $pageNumber, $linkPhanTrang);
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var SoDongHienThi = function(evalue) {
        var linkPhanTrang = '/index.php?module=quanlythuoc&controller=danhmuc&action=index&indexPage=1&pageNumber=[j]';
        linkPhanTrang = linkPhanTrang.replace("[j]", evalue);
        window.location.href = linkPhanTrang;
    }
</script>