<ol class="breadcrumb">
    <li><a href="/index.php?controller=backend">Home</a></li>
    <li><a href="/index.php?controller=quanlyusers">Quản lý file hướng dẫn</a></li>
    <li> Sửa file hướng dẫn </li>
</ol>
<div class="container-fluid">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Sửa file hướng dẫn </h3>
            <div class="box-tools">
                <!--<a href="#" class="btn btn-success" ><i class="fa fa-plus" ></i></a>-->
            </div>
        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-md-6">
                    
                </div>
            </div>
        </div>
    </div>
</div>