<ol class="breadcrumb">
    <li><a href="/index.php?controller=backend">Home</a></li>
    <li><a href="/donthuoc/">Quản lý đơn thuốc</a></li>
    <li> Sửa file hướng dẫn </li>
</ol>
<div class="container-fluid">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Sửa file hướng dẫn </h3>
            <div class="box-tools">
                <!--<a href="#" class="btn btn-success" ><i class="fa fa-plus" ></i></a>-->
            </div>
        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-md-12">
                    <form action="" method="post">
                        <?php
                        use Model\HuongDan\FormHuongDan;
                        $form = new FormHuongDan();
                        $id = $this->getParams(0);
                        $path = "public/huongdan/{$id}.html";
                        $content = file_get_contents($path);
                        echo $form->Content($content)->render();
                        ?>
                        <div class="box-footer">
                            <input type="submit" class="btn btn-success" name="Luu" value="Cập nhật nội dung hướng dẫn " />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>