<ol class="breadcrumb">
    <li><a href="/index.php?controller=backend">Dashboard</a></li>
    <!-- <li><a href="/index.php?controller=thongke">Thống kê</a></li> -->
    <li class="text-capitalize"> Danh sách đơn thuốc trong ngày </li>
</ol>
<?php

use Module\donthuoc\Model\DonThuoc;

?>
<div class="container-fluid">
    <div class="clearfix">
        <div class="box box-primary">
            <div class="box-header">
                <div class="box-tools full-right">
                    <?php
                    if (
                        \Model\Permission::CheckPremision([
                                \Model\User::QuanLy, \Model\User::Admin,
                        ], []) == true
                    ) {
                        ?>
                        <a class="btn btn-success" href="/thongke/exportdonthuoctrongngay/">
                            <i class="fa fa-filter"></i> Export
                        </a>
                        <?php
                    }
                    ?>
                </div>
                <div class="box-body">
                    <form method="get" action="/thongke/donthuoctrongngay/">
                        <div class="col-md-3">
                            <div class="row">
                                <div class="form-group ">
                                    <input id="keyword" class="form-control" name="keyword"
                                        value="<?php echo isset($_GET["keyword"]) ? \Model\Common::TextInput($_GET["keyword"]) : "" ?>"
                                        type=""
                                        placeholder="Nhập vào mã đơn thuốc, tên bệnh nhân hoặc loại đơn thuốc để tìm kiếm">
                                    <input name="indate" value="<?php echo date("Y-m-d", time()); ?>" type="hidden">
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <button class="btn btn-primary no-border-radius" name="btnTim" type="submit">
                                <i class="fa fa-search"></i> Tìm Kiếm
                            </button>
                        </div>


                    </form>
                    <div class="row">
                        <div class="col-sm-12">
                            <table class="table table-hover table-bordered">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>STT</th>
                                        <th>Mã đơn thuốc</th>
                                        <th>Thuộc loại đơn</th>
                                        <th>Tên bệnh nhân</th>
                                        <th>Giới Tính</th>
                                        <th>Ngày Sinh</th>
                                        <th>Thời gian khám bệnh</th>
                                        <th>Chẩn đoán</th>
                                        <th>Tình trạng</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                    $danhsach = $data['items'];
                                    foreach ($danhsach as $index => $item) {
                                        $_item = new DonThuoc($item);
                                        // var_dump($_item);
                                        ?>
                                        <tr>
                                            <td class="text-center">
                                                <div class="dropdown">
                                                    <button class="btn btn-secondary dropdown-toggle" type="button"
                                                        id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true"
                                                        aria-expanded="false">
                                                        <i class="fa fa-ellipsis-v"></i>
                                                    </button>
                                                    <div class="dropdown-menu table-dropdown-menu"
                                                        aria-labelledby="dropdownMenuButton">
                                                        <?php
                                                        echo \Module\donthuoc\Model\btnHtml::btnCopyDonThuoc($_item->Id);
                                                        echo \Module\donthuoc\Model\btnHtml::btnSuaDonThuoc($_item->Id);
                                                        echo \Module\donthuoc\Model\btnHtml::btnchitiet($_item->Id);
                                                        ?>
                                                    </div>
                                                </div>
                                                
                                            </td>
                                            <td class="text-center">
                                                <?php echo (($indexPage - 1) * $pageNumber) + $index + 1; ?>
                                            </td>
                                            <td>
                                                <?php echo $_item->Id; ?>
                                            </td>
                                            <td>
                                                <?php echo $_item->ThuocLoaiDon(); ?>
                                            </td>
                                            <td>
                                                <?php echo $_item->NameBN; ?>
                                            </td>
                                            <td>
                                                <?php echo $_item->Gioitinh(); ?>
                                            </td>
                                            <td>
                                                <?php echo $_item->NgaySinh; ?>
                                            </td>
                                            <td>
                                                <?php echo $_item->ThoiGianKham; ?>
                                            </td>
                                            <td>
                                                <?php echo $_item->ChanDoanBenh; ?>
                                            </td>
                                            <!-- <td><?php echo $_item->TongNgayDung . " " . "Ngày"; ?></td> -->
                                            <td>
                                                <?php echo $_item->Status(); ?>
                                            </td>
                                        </tr>
                                        <?php
                                    }
                                    ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="box-footer">
                        <div class="d-flex">
                            <?php
                            \Model\FormCommon::Select(
                                "",
                                "",
                                [10, 20, 50, 100],
                                [
                                    "style" => "max-width:150px;",
                                    "class" => "form-control",
                                    "value" => $pageNumber,
                                    "onchange" => "SoDongHienThi(this.value)",
                                ]
                            )->render();
                            ?>
                            <?php
                            $linkPhanTrang = "/index.php?controller=thongke&action=donthuoctrongngay&keyword={$params["keyword"]}&indexPage=[i]&pageNumber={$pageNumber}";
                            echo \Model\Common::PhanTrang($total, $indexPage, $pageNumber, $linkPhanTrang);
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var SoDongHienThi = function (evalue) {
        var linkPhanTrang = '/index.php?controller=thongke&action=donthuoctrongngay&indexPage=1&pageNumber=[j]';
        linkPhanTrang = linkPhanTrang.replace("[j]", evalue);
        window.location.href = linkPhanTrang;
    }
</script>