<ol class="breadcrumb">
    <li><a href="/backend/"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
    <li class="active">Thống kê</li>
</ol>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box box-solid">
                    <div class="box-header with-border">
                        <h3 style="letter-spacing: 0.8px;">Thống kê danh sách</h3>

                        <div class="box-tools">
                            <?php
                            use Model\FormRender;
                            FormRender::HuongDan("HuongDanThongKe");
                            ?>
                            <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        </div>
                    </div>
                    <div class="box-body no-padding">
                        <ul style="font-size: 16px;" class="nav nav-pills nav-stacked">
                            <li class="active"><a href="/thongke/thuocsaphet"><i class="fa fa-battery-quarter"></i> Danh sách thuốc sắp hết</a></li>
                            <li><a href="#"><i class="fa fa-envelope-o"></i> Sent</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>