<ol class="breadcrumb">
    <li><a href="/backend/"><i class="fa fa-dashboard"></i> Trang chủ</a></li>
    <li><a href="/thongke/">Thống kê</a></li>
    <li class="active">Danh sách thuốc sắp hết</li>
</ol>
<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-success">
                <div class="box-header">
                    <h3 style="text-align: center;">Danh sách thuốc sắp hết</h3>
                    <div class="box-tools">
                        <a class="btn btn-success" href="/thongke/exportthuocsaphet">
                            <i class="fa fa-filter"></i> Export</a>
                    </div>
                </div>

                <div class="box-body">
                    <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                        <div class="row">
                            <div class="col-sm-6"></div>
                            <div class="col-sm-6"></div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                                    <thead>
                                        <tr role="row">
                                            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending">STT</th>
                                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Tên thuốc</th>
                                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Tên biệt dược</th>
                                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending">Còn lại</th>
                                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Số lô</th>
                                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Nhà sản xuất</th>
                                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Nước sản xuất</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php

                                        use Model\Notions;
                                        use Model\ThongKe;

                                        $index = 0;
                                        $thongke = new ThongKe();
                                        $a = $thongke->GetSpCanhBao();
                                        // var_dump($a);
                                        foreach ($a as $value) { ?>
                                            <tr role="row" class="even">
                                                <td class="sorting_1 text-center"><?php echo $index + 1 ?></td>
                                                <td><?php echo $value['Name'] ?></td>
                                                <td><?php echo $value['Namebietduoc'] ?></td>
                                                <td class="text-center"><?php echo $value['Soluong'] ?></td>
                                                <td class="text-center"><?php echo $value['Solo'] ?></td>
                                                <td><?php echo $value['NhaSX'] ?></td>
                                                <td><?php echo Notions::GetById($value['NuocSX']) ?></td>
                                            </tr>
                                        <?php
                                            $index++;
                                        }
                                        ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>