<ol class="breadcrumb">
    <li><a href="/index.php?controller=backend">Home</a></li>
    <li><a href="/index.php?controller=thongke">Thống kê</a></li>
    <li> Danh sách thuốc sắp hết </li>
</ol>
<?php

use Model\Common;
use Module\benhnhan\Model\BenhNhan;
use Model\Locations;
use Model\ThongKe;

?>
<div class="container-fluid">
    <form method="get" action="/thongke/thuocsaphet/">
        <div class="form-group d-flex">
            <label class="btn btn-default"><input ng-change="isShowMore(showMore);" ng-model="showMore" style="display: none" type="checkbox"><i class="fa fa-share" aria-hidden="true"></class=></i></label>
            <input id="keyword" class="form-control" name="keyword" value="<?php echo isset($_GET["keyword"]) ? \Model\Common::TextInput($_GET["keyword"]) : "" ?>" type="" placeholder="Nhập tên, số điện thoại hoặc địa chỉ để tìm kiếm">
            <button class="btn btn-primary no-border-radius" name="btnTim" type="submit">
                <i class="fa fa-search"></i> Tìm Kiếm
            </button>
        </div>
    </form>
    <div class="clearfix">
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title">Danh sách thuốc sắp hết</h3>
                <div class="box-tools">
                </div>
            </div>
            <div class="box-body">
                <table id="example2" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="example2_info">
                    <thead>
                        <tr role="row">
                            <th class="sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending">STT</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Tên thuốc</th>
                            
                            <th class="sorting text-center" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending">Còn lại</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Số lô</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Nhà sản xuất</th>
                            <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Nước sản xuất</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php

                        use Model\Notions;

                        $index = 0;
                        $danhsach = $data['items'];
                        // var_dump($danhsach);
                        foreach ($danhsach as $value) { ?>
                            <tr role="row" class="even">
                                <td class="sorting_1 text-center"><?php echo $index + 1 ?></td>
                                <td><?php echo $value['Name'] ?></td>
                                <td class="text-center"><?php echo $value['SLHienTai']. " " ."Sản phẩm" ?></td>
                                <td class="text-center"><?php echo $value['Solo'] ?></td>
                                <td><?php echo $value['NhaSX'] ?></td>
                                <td><?php echo Notions::GetById($value['NuocSX']) ?></td>
                            </tr>
                        <?php
                            $index++;
                        }
                        ?>
                    </tbody>
                </table>
                <div class="box-footer">
                    <div class="d-flex">
                        <?php
                        \Model\FormCommon::Select(
                            "",
                            "",
                            [10, 20, 50, 100],
                            [
                                "style" => "max-width:150px;",
                                "class" => "form-control",
                                "value" => $pageNumber,
                                "onchange" => "SoDongHienThi(this.value)",
                            ]
                        )->render();
                        ?>
                        <?php
                        $linkPhanTrang = "/index.php?controller=thongke&action=thuocsaphet&keyword={$params["keyword"]}&indexPage=[i]&pageNumber={$pageNumber}";
                        echo \Model\Common::PhanTrang($total, $indexPage, $pageNumber, $linkPhanTrang);
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var SoDongHienThi = function(evalue) {
        var linkPhanTrang = '/index.php?controller=thongke&action=thuocsaphet&indexPage=1&pageNumber=[j]';
        linkPhanTrang = linkPhanTrang.replace("[j]", evalue);
        window.location.href = linkPhanTrang;
    }
</script>