<ol class="breadcrumb">
    <li><a href="/index.php?controller=backend">Home</a></li>
    <li><a href="/index.php?module=quanlythuoc&controller=phieuxuatnhap&action=index"> Danh Sách Phiếu</a></li>
    <li> Thông Tin Chi Tiết Của Phiếu </li>
</ol>
<?php

use Model\Common;
use Model\OptionsService;
use Module\quanlythuoc\Model\PhieuXuatNhap;
use Module\quanlythuoc\Model\PhieuXuatNhapChiTiet;

$roleDetail = new Model\Role();
?>
<div class="container">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Thông Tin Chi Tiết Của Phiếu</h3>
        </div>
        <div class="box-body">
            <?php
            $itemSP = new PhieuXuatNhap($data);
            ?>
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <table class="table ">
                    <tr>
                        <td class="text-right">Mã Phiếu</td>
                        <td><?php echo $itemSP->IdPhieu ?></td>
                    </tr>

                    <tr>
                        <td class="text-right">Loại phiếu</td>
                        <td><?php echo $itemSP->XuatNhap(); ?></td>
                    </tr>
                    <tr>
                        <td class="text-right">Tổng tiền</td>
                        <td><?php echo $itemSP->getTongTien(); ?></td>
                    </tr>
                    <tr>
                        <td class="text-right">Nội Dung</td>
                        <td><?php echo $itemSP->NoiDungPhieu ?></td>
                    </tr>
                    <tr>
                        <td class="text-right">Ghi chú</td>
                        <td><?php echo $itemSP->GhiChu ?></td>
                    </tr>
                </table>
            </div>

            <div class="col-md-12">
            
                <table class="table ">
                    <tr>
                        <th>Thuốc</th>
                        <th>Số lượng</th>
                        <th>Số Lô</th>
                        <th>Nhà sản xuất</th>
                        <th>Nơi sản xuất</th>
                        <th>Giá</th>
                        <th>Thành tiền</th>
                    </tr>
                    <?php
                    foreach ($itemSP->PhieuChiTiet() as $key => $value) {
                        $_chiTiet = new PhieuXuatNhapChiTiet($value);
                    ?>
                        <tr>
                            <td><?php echo $_chiTiet->SanPham()->Name ?></td>
                            <td><b><?php echo $_chiTiet->SoLuong ?></b></td>
                            <td><?php echo $_chiTiet->SoLo ?></td>
                            <td><?php echo $_chiTiet->NhaSanXuat ?></td>
                            <td><?php echo $_chiTiet->NuocSanXuat ?></td>
                            <td><b><?php echo $_chiTiet->Price() ?></b></td>
                            <td><b><?php echo $_chiTiet->ThanhTien(); ?></b></td>
                        </tr>
                    <?php
                    }
                    ?>
                    <tr> 
                        <td colspan="6" class="text-right" > Tổng Tiền</td>
                        <td><b><?php echo $itemSP->getTongTien(); ?></b></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>