<ol class="breadcrumb">
    <li><a href="/index.php?controller=backend">Home</a></li>
    <li><a href="/index.php?module=quanlythuoc&controller=phieuxuatnhap&action=index"> Danh Sách Phiếu</a></li>
    <li> Thông Tin Chi Tiết Của Phiếu </li>
</ol>
<?php

use Model\Common;
use Model\OptionsService;
use Module\quanlythuoc\Model\PhieuXuatNhap;

$roleDetail = new Model\Role();
?>
<div class="container-fluid">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Thông Tin Chi Tiết Của Phiếu</h3>
        </div>
        <!-- <div class="box-body"> -->
        <form action="" method="post" enctype="multipart/form-data">
            <div class="box-body">
                <?php

                $itemSP = new PhieuXuatNhap($data);

                // var_dump($itemSP);

                ?>
                <div class="">
                    <div class="col-md-4">
                        <label for="">Mã Phiếu</label>
                        <input readonly value="<?php echo $itemSP->Id; ?>" class="form-control">
                    </div>
                    <div class="col-md-4">
                        <label for="">Loại Phiếu</label>
                        <input readonly value="<?php echo $itemSP->IdPhieu; ?>" class="form-control">
                    </div>
                    <div class="col-md-4">
                        <label for="">Mã Thuốc</label>
                        <input readonly value="<?php echo $itemSP->IdThuoc; ?>" class="form-control">
                    </div>
                    <div class="col-md-4">
                        <label for="">Số Lượng</label>
                        <input readonly value="<?php echo Common::ViewNumber($itemSP->SoLuong); ?>" class="form-control">
                    </div>
                    <div class="col-md-4">
                        <label for="">Số Lô</label>
                        <input readonly value="<?php echo $itemSP->SoLo ?>" class="form-control">
                    </div>
                    <div class="col-md-4">
                        <label for="">Nhà Sản Xuất</label>
                        <input readonly value="<?php echo $itemSP->NhaSanXuat; ?>" class="form-control">
                    </div>
                    <div class="col-md-4">
                        <label for="">Nước Sản Xuất</label>
                        <input readonly value="<?php echo $itemSP->NuocSanXuat; ?>" class="form-control">
                    </div>
                    <div class="col-md-4">
                        <label for="">Giá</label>
                        <input readonly value="<?php echo Common::ViewPrice($itemSP->Price); ?>" class="form-control">
                    </div>
                    <div class="col-md-4">
                        <label for="">Xuất/Nhập</label>
                        <input readonly value="<?php echo $itemSP->XuatNhap; ?>" class="form-control">
                    </div>
                    <div class="col-md-4">
                        <label for="">Ngày Tạo</label>
                        <input readonly value="<?php echo $itemSP->CreateRecord; ?>" class="form-control">
                    </div>
                    <div class="col-md-4">
                        <label for="">Ngày Update</label>
                        <input readonly value="<?php echo $itemSP->UpdateRecord; ?>" class="form-control">
                    </div>
                    <div class="col-md-4">
                        <label for="">Ngày Nhập</label>
                        <input readonly value="<?php echo $itemSP->NgayNhap; ?>" class="form-control">
                    </div>
                    <div class="col-md-6">
                        <label for="">Nội Dung Phiếu</label>
                        <textarea rows="5" readonly class="form-control"><?php echo $itemSP->NoiDungPhieu; ?></textarea>
                    </div>
                    <div class="col-md-6">
                        <label for="">Ghi Chú</label>
                        <textarea rows="5" readonly class="form-control"><?php echo $itemSP->GhiChu; ?></textarea>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<script src="/public/TinhThanh/tinhthanh.js"></script>