<ol class="breadcrumb">
    <li><a href="/index.php?controller=backend">Home</a></li>
    <li><a href="index.php?module=quanlythuoc&controller=phieuxuatnhap&action=index"> Danh Sách Phiếu</a></li>
    <li> Thêm Phiếu </li>
</ol>
<?php

use Module\quanlythuoc\Model\DanhMuc;
use Module\quanlythuoc\Model\DanhMuc\FormDanhMuc;
use Module\quanlythuoc\Model\PhieuXuatNhap;
use Module\quanlythuoc\Model\PhieuXuatNhap\FormPhieuXuatNhap;

$roleDetail = new Model\Role();
?>
<div class="container-fluid">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Thêm Phiếu</h3>
            <!-- <div class="box-tools">
                <?php
                Module\quanlythuoc\Model\btnHtml::btnViewDanhMuc();
                ?>
            </div> -->
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            <div class="box-body">
                <?php
                $phieu = new FormPhieuXuatNhap();
                ?>
                <div class="">
                    <div class="col-md-4">
                        <?php $phieu->IdPhieu()->renderHtml(); ?>
                    </div>
                    <div class="col-md-4">
                        <?php $phieu->XuatNhap()->renderHtml(); ?>
                    </div>
                    <div class="col-md-4">
                        <?php $phieu->NgayNhap()->renderHtml();  ?>
                    </div>
                    <div class="col-md-6">
                        <?php $phieu->NoiDungPhieu()->renderHtml();  ?>
                    </div>
                    <div class="col-md-6">
                        <?php $phieu->GhiChu()->renderHtml();  ?>
                    </div>
                    <div class="col-md-12">
                        <fieldset>
                            <legend>Danh Sách Thuốc</legend>
                            <div>
                                <button class="btn btn-success" id="btn-addrow"><i class="fa fa-plus" aria-hidden="true"></i></button>
                            </div>
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>STT</th>
                                        <th>Mã Thuốc</th>
                                        <th>Số Lượng</th>
                                        <th>Số Lô</th>
                                        <th>Nhà Sản Xuất</th>
                                        <th>Nước Sản Xuất</th>
                                        <th>Giá</th>
                                    </tr>
                                </thead>
                                <tbody class="table-thuoc">

                                    <?php
                                    // var_dump(PhieuXuatNhap::DSThuocPhieuNhap());
                                    $i = 0;
                                    foreach (PhieuXuatNhap::DSThuocPhieuNhap() as $mathuoc => $thuoc) {

                                        var_dump($thuoc);
                                        // $sanPham = new PhieuXuatNhap($thuoc["Id"] ?? null);
                                        // var_dump($sanPham);
                                    ?>
                                        <tr>
                                            <th>
                                                <button class="btn btn-danger deleterow" id="<?php echo 'delete'. $i ?>" index =<?php echo $i + 1?>><i class="fa fa-minus" aria-hidden="true"></i></button>
                                            </th>
                                            <th>
                                                <?php echo $i + 1; ?>
                                            </th>
                                            <th style="width: 200px;">
                                                <?php echo $phieu->IdThuoc($thuoc["IdThuoc"] ?? "", "IdThuoc" . $i, $i)->render() ?>
                                            </th>
                                            <th>
                                                <?php echo $phieu->SoLuong("", "SoLuong" . $i, $i)->render(); ?>
                                            </th>
                                            <th>
                                                <?php echo $phieu->SoLo("", "SoLo" . $i, $i)->render(); ?>
                                            </th>
                                            <th>
                                                <?php echo $phieu->NhaSanXuat("", "NhaSanXuat" . $i, $i)->render(); ?>
                                            </th>
                                            <th>
                                                <?php echo $phieu->NuocSanXuat("", "NuocSanXuat" . $i, $i)->render(); ?>
                                            </th>
                                            <th>
                                                <?php echo $phieu->Price("", "Price" . $i, $i)->render(); ?>
                                            </th>
                                        </tr>
                                    <?php
                                        $i++;
                                    }
                                    ?>
                                </tbody>
                            </table>
                        </fieldset>
                    </div>
                    <script>
                    $(document).ready(function() {
                        $(".deleterow").click(function() {
                            var index = $("#" + $(this).attr("id")).attr("index");
                            // var TongNgayDungThuoc = $("#TongNgayDungThuoc").val();
                            $.ajax({
                                url: `/quanlythuoc/phieuxuatnhap/DeleteSP/${index}/`,
                                type: 'Get',
                                // data:{$id : $id},
                                //dataType: 'json',
                                contentType: false,
                                processData: false,
                                success: function(response) {
                                    console.log(response);
                                    window.location.reload();
                                },
                                complete: function() {
                                    //spinner.close();
                                }
                            });
                        })


                        $("#btn-addrow").click(function() {
                            // var index = $("#" + $(this).attr("id")).attr("index");
                            // alert("index");
                            // var TongNgayDungThuoc = $("#TongNgayDungThuoc").val();
                            $.ajax({
                                url: `/quanlythuoc/phieuxuatnhap/ThemSanPham/`,
                                type: 'post',
                                // data:{$id : $id},
                                //dataType: 'json',
                                contentType: false,
                                processData: false,
                                success: function(response) {
                                    console.log(response);
                                    window.location.reload();
                                },
                                complete: function() {
                                    //spinner.close();
                                }
                            });
                        })


                        $(".changename").each(function(index, e) {
                            // console.log(e.attr("id"));
                            $(this).change(function(param) {
                                // console.log($(this).attr("id")); // Lấy Id thuốc
                                $($(this).attr("id")).val();
                                // console.log($("#"+$(this).attr("id")).val()); // Lấy Mã Thuốc
                                // console.log($("#" + $(this).attr("id")).attr("index")); // Lấy index thuốc
                                var idName = "#" + $(this).attr("id");
                                var idDVT = "#dvt" + $("#" + $(this).attr("id")).attr("index");
                                var index = $("#" + $(this).attr("id")).attr("index");
                                var idThuoc = $(idName).val();

                                // console.log(idDVT);
                                console.log(index);
                                console.log(idName);
                                console.log(idThuoc);

                                $.ajax({
                                    url: `/quanlythuoc/phieuxuatnhap/capnhatdanhsachsanpham/${idThuoc}/${index}/`,
                                    type: 'Get',
                                    // data:{$id : $id},
                                    //dataType: 'json',
                                    contentType: false,
                                    processData: false,
                                    success: function(response) {
                                        console.log(response);
                                        // console.log("ádasdsadsdadasdsd");
                                        if (response.SoNgaySDThuoc == null) {
                                            alert("Thuốc đã có trong danh sách");
                                            console.log(idName);
                                            window.location.reload();
                                            $(idName).val("");
                                            console.log($(idName + " option:selected").val());
                                            return;
                                        }
                                        console.log(response);
                                        $(idGiaBan).val(response.Giaban);
                                        $(idDVT).val(response.DVTTitle);
                                        $(idSang).val(response.Sang);
                                        $(idTrua).val(response.Trua);
                                        $(idChieu).val(response.Chieu);
                                        $(idSoNgaySD).val(response.SoNgaySDThuoc);
                                        $(idSoLuong).val(response.Soluong);
                                        $(idCachDungThuoc).val(response.CachDung);
                                        $(idGhiChu).val(response.Ghichu);
                                    },
                                    complete: function() {
                                        //spinner.close();
                                    }
                                });
                            });
                        });

                        
                    });
                </script>
                    <div class="col-md-12 ">
                        <button class="btn btn-warning" type="reset">Làm Lại</button>
                        <!-- <button class="btn btn-success">Lưu</button> -->
                        <button class="btn btn-success" name="LuuThoat">Thêm Mới</button>
                    </div>
                </div>
        </form>
    </div>
</div>
</div>