<ol class="breadcrumb">
    <li><a href="/index.php?controller=backend">Home</a></li>
    <li><a href="index.php?module=quanlythuoc&controller=phieuxuatnhap&action=index"> Danh Sách Phiếu</a></li>
    <li> Thêm Phiếu </li>
</ol>
<?php

use Module\quanlythuoc\Model\DanhMuc;
use Module\quanlythuoc\Model\DanhMuc\FormDanhMuc;
use Module\quanlythuoc\Model\PhieuXuatNhap\FormPhieuXuatNhap;

$roleDetail = new Model\Role();
?>
<div class="container-fluid">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Thêm Phiếu</h3>
            <!-- <div class="box-tools">
                <?php
                Module\quanlythuoc\Model\btnHtml::btnViewDanhMuc();
                ?>
            </div> -->
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            <div class="box-body">
                <?php
                $phieu = new FormPhieuXuatNhap();
                ?>
                <div class="">
                    <div class="col-md-4">
                        <?php $phieu->IdPhieu()->renderHtml(); ?>
                    </div>
                    <div class="col-md-4">
                        <?php $phieu->XuatNhap()->renderHtml(); ?>
                    </div>
                    <div class="col-md-4">
                        <?php $phieu->NgayNhap()->renderHtml();  ?>
                    </div>
                    <div class="col-md-6">
                        <?php $phieu->NoiDungPhieu()->renderHtml();  ?>
                    </div>
                    <div class="col-md-6">
                        <?php $phieu->GhiChu()->renderHtml();  ?>
                    </div>
                    <div class="col-md-12">
                        <fieldset>
                            <legend>Danh Sách Thuốc</legend>
                            <div>
                                <button class="btn btn-success"><i class="fa fa-plus" aria-hidden="true"></i></button>
                            </div>
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>STT</th>
                                        <th>Mã Thuốc</th>
                                        <th>Số Lượng</th>
                                        <th>Số Lô</th>
                                        <th>Nhà Sản Xuất</th>
                                        <th>Nước Sản Xuất</th>
                                        <th>Giá</th>
                                    </tr>
                                </thead>
                                <tbody class="table-thuoc">
                                    <?php
                                    $i = 0;
                                    foreach (DonThuocDetail::DsThuoc() as $mathuoc => $thuoc) {
                                        // var_dump($thuoc);
                                        $sanPham = new SanPham($thuoc["Id"] ?? null);
                                        // var_dump($sanPham);
                                    ?>
                                        <tr>
                                            <th>
                                                <button class="btn btn-danger"><i class="fa fa-minus" aria-hidden="true"></i></button>
                                            </th>
                                            <th>
                                                <?php
                                                echo $phieu->IdThuoc()->render() ?>
                                            </th>
                                            <th>
                                                <?php echo $phieu->SoLuong()->render(); ?>
                                            </th>
                                            <th>
                                                <?php echo $phieu->SoLo()->render(); ?>
                                            </th>
                                            <th>
                                                <?php echo $phieu->NhaSanXuat()->render(); ?>
                                            </th>
                                            <th>
                                                <?php echo $phieu->NuocSanXuat()->render(); ?>
                                            </th>
                                            <th>
                                                <?php echo $phieu->Price()->render(); ?>
                                            </th>
                                        </tr>
                                    <?php
                                        $i++;
                                    }
                                    ?>
                                </tbody>
                            </table>
                        </fieldset>
                    </div>
                    <div class="col-md-12 ">
                        <button class="btn btn-warning" type="reset">Làm Lại</button>
                        <!-- <button class="btn btn-success">Lưu</button> -->
                        <button class="btn btn-success" name="LuuThoat">Thêm Mới</button>
                    </div>
                </div>
        </form>
    </div>
</div>
</div>