<ol class="breadcrumb">
    <li><a href="/index.php?controller=backend">Home</a></li>
    <li><a href="index.php?module=quanlythuoc&controller=phieuxuatnhap&action=index"> Danh Sách Phiếu</a></li>
    <li> Sửa Phiếu </li>
</ol>
<?php

use Module\quanlythuoc\Model\DanhMuc;
use Module\quanlythuoc\Model\DanhMuc\FormDanhMuc;
use Module\quanlythuoc\Model\PhieuXuatNhap;
use Module\quanlythuoc\Model\PhieuXuatNhap\FormPhieuXuatNhap;

$roleDetail = new Model\Role();
?>
<div class="container-fluid">
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">Sửa Phiếu</h3>
            <!-- <div class="box-tools">
                <?php
                Module\quanlythuoc\Model\btnHtml::btnViewDanhMuc();
                ?>
            </div> -->
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            <div class="box-body">
                <?php
                $phieu = new FormPhieuXuatNhap();
                $_item = new PhieuXuatNhap($data);
                ?>
                <div class="">
                    <div class="col-12">
                        <?php $phieu->Id($_item->Id)->render();  ?>
                    </div>
                    <div class="col-md-6">
                        <?php $phieu->IdThuoc($_item->IdThuoc)->renderHtml();  ?>
                    </div>
                    <div class="col-md-6">
                        <?php $phieu->NgayNhap($_item->NgayNhap)->renderHtml();  ?>
                    </div>
                    <div class="col-md-6">
                        <?php $phieu->XuatNhap($_item->XuatNhap)->renderHtml();  ?>
                    </div>
                    <div class="col-md-6">
                        <?php $phieu->SoLuong($_item->SoLuong)->renderHtml();  ?>
                    </div>
                    <div class="col-md-6">
                        <?php $phieu->SoLo($_item->SoLo)->renderHtml();  ?>
                    </div>
                    <div class="col-md-6">
                        <?php $phieu->NhaSanXuat($_item->NhaSanXuat)->renderHtml();  ?>
                    </div>
                    <div class="col-md-6">
                        <?php $phieu->NuocSanXuat($_item->NuocSanXuat)->renderHtml();  ?>
                    </div>
                    <div class="col-md-6">
                        <?php $phieu->Price($_item->Price)->renderHtml();  ?>
                    </div>
                    <div class="col-md-6">
                        <?php $phieu->NoiDungPhieu($_item->NoiDungPhieu)->renderHtml();  ?>
                    </div>
                    <div class="col-md-6">
                        <?php $phieu->GhiChu($_item->GhiChu)->renderHtml();  ?>
                    </div>

                    <div class="col-md-12 ">
                        <button class="btn btn-warning" type="reset">Làm Lại</button>
                        <!-- <button class="btn btn-success">Lưu</button> -->
                        <button class="btn btn-success" name="LuuThoat">Sửa Phiếu</button>
                    </div>
                </div>
        </form>
    </div>
</div>
</div>